### ISSUE TITLE
Don't keep connection open for correspondence games

### ISSUE THREAD

**Issue by koedem** [ShailChoksi/lichess-bot#173]
When dealing with correspondence games it is not necessary to keep the connection open, instead one can open a connection, poll for new moves, then close it again and wait for e.g. 10 minutes.
The problem with the current way is when playing e.g. 10 correspondence games the client opens 10 connections to lichess which gets blocked as potential DDoS attack.

**Comment by MarkZH** [comment]
This was implemented in PR #316.
