### ISSUE TITLE
Write bot move info (eval, pv, depth) into a pgn

### ISSUE THREAD

**Issue by koedem** [ShailChoksi/lichess-bot#175]
The simplest way to do this would probably be to always write to some local pgn file, e.g. with the pgn name being the game id. (that way even through dis- and reconnecting it should (?) still write to the same file)
Then for now the bot maintainer can upload the pgn manually into some study or similar although later it might also be interesting to add an "!analysis" command that spectators or the opponent can use to have the bot automatically upload the pgn into a study after the game, provided there is a lichess api endpoint for that.

As for what should be written in there, I think the relevant infos are 1. pv 2. eval 3. depth.

**Comment by MarkZH** [comment]
This has been implemented in PR #444.
