### ISSUE TITLE
Engine directory

### ISSUE THREAD

**Issue by krishna134** [ShailChoksi/lichess-bot#179]
`
![Screenshot (6)](https://user-images.githubusercontent.com/52482588/60567689-652be780-9d88-11e9-8d66-5f37b69d8e56.png)
 How to Solve this problem ? It is saying that Your Engine Directory is not a Diectory
`

**Comment by careless25** [comment]
You are running the command in the wrong directory. 
Do the following: 
```
cd ..
python lichess-bot.py -u
```
