### ISSUE TITLE
Problems resigning with xboard

### ISSUE THREAD

**Issue by thomasahle** [ShailChoksi/lichess-bot#191]
I'm getting the following error when my bot tries to resign: `2020-02-13 01:18:21,379: Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/cCTWbpc2/move/-1)`

Looking at the `xboard` log, things look good:
```
>>> usermove f1f2
>>> time 3480
>>> otim 5279
>>> go
  1    -1380        0            32 	f8e7
...
  7   -69290      112         41207 	g7g6 f2g1
resign
>>> result 1-0
>>> quit
```

Is this a problem with the lichess servers? The lichess-bot script? Or with my bot?

**Comment by thomasahle** [comment]
I suppose this is due to https://github.com/ShailChoksi/lichess-bot/issues/79

**Comment by steven-xia** [comment]
The `lichess-bot` script currently does not support resigning.

**Comment by ShailChoksi** [comment]
I am closing due to this: https://github.com/ShailChoksi/lichess-bot/issues/79#issuecomment-386016057
