### ISSUE TITLE
Question: How to resign in UCI

### ISSUE THREAD

**Issue by SquarishRectangle** [ShailChoksi/lichess-bot#198]

**Comment by SquarishRectangle** [comment]
I know uci doesn't officially support resigning but can we just add a special command like "bestmove resign" or sth? 
Or is such a command already in use?

**Comment by MarkZH** [comment]
Any engine can now choose to resign using the config.yml file. See the `draw_or_resign` section in the [README](https://github.com/ShailChoksi/lichess-bot#engine-configuration).
