### ISSUE TITLE
Moves repeated in correspondance mode

### ISSUE THREAD

**Issue by thomasahle** [ShailChoksi/lichess-bot#199]
I enabled correspondence mode for my bot.
This turned out to be a bad idea, since people would challenge it to infinite time games, in which the bot would never move.
I then killed the bot, disabled correspondence mode and started the bot back up.
However, the correspondence game was still active, and I got the following commands over UCI:
```
>>> force
>>> setboard rnbqkbnr/ppp1pppp/8/3p4/8/2N5/PPPPPPPP/R1BQKBNR w KQkq - 0 2
>>> level 0 5256000:0 0
>>> force
>>> usermove d7d5
```
Notice that in this FEN position, the move d7d5 has already been played by my opponent, so when it gets sent again with `usermove` my bot crashes.

Overall I think the way correspondence is implemented is fine,
but there seems to be a bug in starting games from a given position.
Either all the moves should be sent with `usermove`, or the `setboard` should just jump directly to the final position.

**Comment by thomasahle** [comment]
Just wanted to comment that this is still an issue, regularly crashing my bot. Here is another example log file:

```
>>> xboard
>>> protover 2
feature done=0
feature myname="Sunfish"
feature usermove=1
feature setboard=1
feature ping=1
feature sigint=0
feature nps=0
feature variants="normal"
feature option="qs_limit -spin 75 -100 1000"
feature option="eval_roughness -spin 22 1 1000"
feature option="draw_test -spin 1 0 1"
feature done=1
>>> post
>>> easy
>>> ping 123
pong 123
>>> force
>>> setboard 3rkb1r/4p1pp/p1Q5/1pp5/8/P1N1B1PB/1q1NKP1P/n6R b k - 3 23
>>> level 0 3:0 0
>>> force
>>> usermove d5c6
```

**Comment by ShailChoksi** [comment]
lichess-bot wasn't meant to work with correspondance mode. You can modify the code to make it work but there will be issues as Lichess correspondance mode works differently from all other modes.

**Comment by MarkZH** [comment]
I think the pull request #195 should fix this.

**Comment by MarkZH** [comment]
I believe this issue is resolved with the overhaul of the python-chess library. I use an xboard engine and have no problem with disconnecting and reconnecting games. Please reopen if the issue persists.
