### ISSUE TITLE
Lichess-bot 1.1.4 error

### ISSUE THREAD

**Issue by SquarishRectangle** [ShailChoksi/lichess-bot#201]
At random times sometimes in the middle of the game, as if on a whim, Lichess-bot, 1.1.4 would crash and I get this error message:

` ` `
Traceback (most recent call last):
  File "lichess-bot.py", line 426, in <module>
    start(li, user_profile, engine_factory, CONFIG)
  File "lichess-bot.py", line 83, in start
    if event["type"] == "terminated":
KeyError: 'type'
` ` `

It would continue for 15 or so minutes during which even if I restart the entire machine it would still output that error. After that period even if I did nothing but wait, it would go away and I can use it like normal again until it's next whim.

**Comment by MarkZH** [comment]
The linked PR (#355) added code to display the message that causes the error instead of displaying a cryptic error message. Please reopen this issue if the error keeps happening.
