### ISSUE TITLE
lichess-bot sends "position" and "go" command after engine got mated

### ISSUE THREAD

**Issue by sander-NULL** [ShailChoksi/lichess-bot#202]
After the engine got mated lichess-bot will send a "position" followed by a "go" command including the mating move. The following is an example of this where the last three UCI commands lichess-bot sent are shown:
`position startpos moves b2b3 e7e5 c1b2 b8c6 d1c1 g8f6 e2e3 d7d5 f1e2 e5e4 e2b5 c8d7 b2a3 f8a3 c1a3 a7a6 b5c6 d7c6 a3b2 e8g8 b2d4 b7b6 d4c3 c6d7 c3e5 f8e8 e5g5 h7h6 g5h4 e8e5 h4f4 e5f5 f4h4 f5h5 h4f4 h5f5 f4h4 f5g5 e1f1 d7b5 c2c4 d5c4 b1a3 c4b3 a3b5 d8d3 f1e1 b3b2 a1d1 g5b5 a2a4 b2b1q g1e2 b1d1 e1d1 b5b2 d1e1 b2d2 e2c3 d3c3 h4g4 f6g4 e1f1 c3c1 c3c1`
`go wtime 64910 btime 122300 winc 0 binc 0`
`quit`
Notice that the mating move (c3c1) is sent twice which causes the engine to send rubbish search data which in turn lets lichess-bot throw an exception:
`exception parsing pv from info: 'depth 2 score cp 1100 pv d2f2 f1e1', position at root: r5k1/2p2pp1/pp5p/8/P3p1n1/4P3/3r1PPP/2q2K1R b - - 0 33`

**Comment by MarkZH** [comment]
Can you try my pull request #216) and see if that fixes the problem?

**Comment by sander-NULL** [comment]
I tried it in one game and at first glance it works.

**Comment by MarkZH** [comment]
Note: this issue is a duplicate if #214.
