### ISSUE TITLE
Double pondering

### ISSUE THREAD

**Issue by aurimus** [ShailChoksi/lichess-bot#210]
Leela, strangely she skipped a move and just went from pondering to pondering.. where she should have made a move. And the lichess bot went offline. Ctrl+C gave an exception

![image](https://user-images.githubusercontent.com/1052992/86282033-245aee80-bbe7-11ea-8d1e-3bc59e7bcf93.png)

**Comment by MarkZH** [comment]
The library code and the pondering code have gone through a lot of changes since this issue was filed. Please update to the latest lichess-bot and let us know if this is still a problem.
