### ISSUE TITLE
The bot isn't playing after the game has started.

### ISSUE THREAD

**Issue by ZeroThink-01** [ShailChoksi/lichess-bot#218]
> 2020-09-13 15:17:38,912: You're now connected to https://lichess.org/ and awaiting challenges.                 
> 2020-09-13 15:17:45,511: Something went wrong. Game is starting and we don't have a queued process
> 2020-09-13 15:17:45,514: --- Process Used. Total Queued: 0. Total Used: 1

**Comment by ZeroThink-01** [comment]
It doesn't start the program.
I can start the program by clicking on it but with lichess-bot file i cannot run it on lichess.

**Comment by lakinwecker** [comment]
It helps if you include the python version number you're using, the OS you're using, the engine you're using and the version of lichess-bot you're using

**Comment by ZeroThink-01** [comment]
Im using Python 3.8 (64-bit) , latest lichess-bot file and Im using Windows, also Im using chess engine written in Python.

**Comment by ZeroThink-01** [comment]
It doesnt start the program. I think its same issue with https://github.com/ShailChoksi/lichess-bot/issues/41 but as i see it solved
many months ago, I don't understand why I get the same error again.

**Comment by ZeroThink-01** [comment]
2020-09-13 23:28:09,561: Starting new HTTPS connection (1): lichess.org:443
2020-09-13 23:28:09,807: https://lichess.org:443 "GET /api/bot/game/stream/MyZiWMpm HTTP/1.1" 200 None
2020-09-13 23:28:09,972: <PopenProcess at 0x19dde1dcf70 (pid=12600)> << uci
