### ISSUE TITLE
lichess-bot accepts draw offer

### ISSUE THREAD

**Issue by sander-NULL** [ShailChoksi/lichess-bot#220]
In this game https://lichess.org/LXCInjNn#4 the human opponent of the bot offers a draw and lichess-bot accepts it. Is that intended? This was not the first time this happened but I can't find the other game right now.

**Comment by MarkZH** [comment]
Can you post a verbose log (`python lichess-bot.py -v`) of a game where a draw is accepted? I just tried with both UCI and Xboard protocols and in neither is a draw acted upon.

**Comment by sander-NULL** [comment]
This is another game where this happened: https://lichess.org/46hEX5K2
The engine uses the UCI protocol. Apparently in this case it was the engines fault sending wrong PV data and a best move that was illegal.
lichess-bot threw a couple of exceptions like
`exception parsing pv from info`
and in the end
`exception parsing bestmove` followed by
`2020-09-18 04:20:36,421: Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/46hEX5K2/move/None)`                 
`*** https://lichess.org/46hEX5K2/white [spectator] lichess: b'Draw offer accepted'`
`*** https://lichess.org/46hEX5K2/white [player] lichess: b'Draw offer accepted'`

Maybe lichess-bot accepts draw offers when it realizes the engine is doing senseless things?
I will also try to capture a game with the above setting.

**Comment by sander-NULL** [comment]
I rechecked the engine's log of the game https://lichess.org/46hEX5K2 and it turns out that lichess-bot sent the following faulty command:
`position startpos moves b2b3 d7d5 e2e3 b8c6 c1b2 e7e5 f1b5 f8d6 b2a3 d6a3 b1a3 c8d7 d1h5 g8f6 h5h4 e8g8 e1e2 f6e4 h4d8 a8d8 f2f3 e4f6 c2c4 d5d4 b5a4 d4d3 e2d1 e5e4 d1c1 c6b4 a4d7 d8d7 f3e4 f6e4 g1h3 c7c6 h1f1 b7b5 f1f4 f8e8 c4b5 c6b5 a3b5 e8c8 c1d1 d7e7 b5a7 c8c2 d1e1 c2d2 e1f1 e7a7 f4e4 h7h6 e4b4 a7c7 b4d4 c7c2 h3f4 d2f2 f1g1 c2a2 d4d8 g8h7 a1a2 f2a2 d8d3 d8d3 a2a1`
Notice that in the last three moves d8d3 appeared twice. This confused the engine and caused the above written. Is that another instance of moves sent twice by lichess-bot but in this case the move was not game ending?

**Comment by MarkZH** [comment]
Yeah, this looks like the same issue as #202 and #214, which would be fixed by pull request #216.

**Comment by MarkZH** [comment]
@sander-NULL  Can you update lichess-bot and see if this problem still occurs?

**Comment by sander-NULL** [comment]
I already pulled the latest version including your PR 216. I'll post here if I encounter that error again. So no news are good news.
