### ISSUE TITLE
How to greet opponents with bot? 

### ISSUE THREAD

**Issue by Jishnu2010** [ShailChoksi/lichess-bot#227]
Hello everyone, I have seen bots greeting their opponents and even conversing with them. I just want to know can I also do that? If yes, please tell me and if not, then no problem I will try to find a way in another platform.

Thanks in advance.

**Comment by MarkZH** [comment]
Chats are handled with the `Conversation` class in the `conversation.py` file. Incoming chat messages are handled by the lines

    if u_type == "chatLine":
        conversation.react(ChatLine(upd), game)

at line 211-212 in `lichess-bot.py`. You can edit these files (especially the `Conversation.react()` method to have your bot respond to incoming chat text from other players.

**Comment by Jishnu2010** [comment]
Thanks for replying. I have edited the `conversation.py` file and it has provided me good results. I am closing this issue now
