### ISSUE TITLE
Setting current directory of engine executable

### ISSUE THREAD

**Issue by cosinekitty** [ShailChoksi/lichess-bot#232]
This is an awesome project. I was able to get my own chess engine [Chenard](https://github.com/cosinekitty/chenard) up and running on linode.org in less than 10 minutes.

The xboard version of my engine reads and writes files from whatever the current directory is. When I run lichess.py from its directory (a clone of this repo), it apparently spawns Chenard with that same directory as the current directory. This causes Chenard's private files to get mixed in with lichess-bot files, which is a little messy.

Is there a way to specify an alternate directory to set as the current directory for the engine's spawned process?  If not, would you be open to me working on a pull request to do that?

It's no big deal because I could just add that feature to my own code via an environment variable telling Chenard where to read/write its private files to. I thought other engines might benefit from this too.

**Comment by MarkZH** [comment]
What's worked for me is to create a script that changes to the desired directory before calling the actual chess program. So, in the file `lichess-bot/engines/my_chess_bot.sh`:

    cd /dir/for/writing/files/
    the_actual_chess_program --option1=value1 # etc.

Then, in `lichess-bot/config.yml`:

    # ...
    engine:
      dir: "./engines/"
      name: "my_chess_bot.sh
    # ...

**Comment by MarkZH** [comment]
@cosinekitty I've created a pull request to implement this directly (#416). Please test if you can.

**Comment by MarkZH** [comment]
Users can now specify a working directory for their engines (#416).
