### ISSUE TITLE
Logger doesn't work in play_game function in lichess_bot.py

### ISSUE THREAD

**Issue by icecream17** [ShailChoksi/lichess-bot#238]
While debugging I found that the logger didn't work
![image](https://user-images.githubusercontent.com/58114641/100299196-abbf4a80-2f58-11eb-9f85-b37584e97ead.png)

Although the logger still exists
![image](https://user-images.githubusercontent.com/58114641/100299900-6bf96280-2f5a-11eb-940e-d9bb5d0978a0.png)

**Comment by MarkZH** [comment]
Are you running lichess-bot with verbose output? `python lichess-bot.py -v`
