### ISSUE TITLE
File Error

### ISSUE THREAD

**Issue by chessBOTneeder** [ShailChoksi/lichess-bot#239]
When I use lichess-bot and it says that I'm connected lichess, and then when I start a game, it says this: Backing off create_engine(...) for 0.3s (OSError: [Errno 8] Exec format error: './engines/stockfish.exe') 

Please Help.

**Comment by zzhangb4** [comment]
Only include the '.exe' in the engine name if you're using Windows. I see you're on linux (OSError: [Errno 8] Exec format error: is a Linux thing) and so you should have name: "stockfish".

Hope this helps!

**Comment by MarkZH** [comment]
Is this still a problem?
