### ISSUE TITLE
python-chess library obsolete

### ISSUE THREAD

**Issue by stevexyz** [ShailChoksi/lichess-bot#240]
The wrapper is using python chess v. 0.24, while the latest is 1.3!
In my case the problem is that my engine use also python chess and the two versions are incompatible (I've just recently updated to last version).
I think that supporting the newer versions should be a welcomed approach to program maintenance.

**Comment by MarkZH** [comment]
I've created a branch that uses python chess 1.3.3.

https://github.com/MarkZH/lichess-bot/tree/python-chess-upgrade-working

I believe the branch is operationally equivalent to the current lichess-bot, but I'll wait to create a pull request until it's been tested by other people. The only difference is that the implementation of the Xboard protocol in python chess 1.3.3 rejects the usermove option.

**Comment by ShailChoksi** [comment]
@MarkZH Thanks for the PR. I will wait to see some more testing on the branch until I am comfortable merging it in.
