### ISSUE TITLE
lichess-bot occasionally crashes

### ISSUE THREAD

**Issue by sander-NULL** [ShailChoksi/lichess-bot#241]
From time to time lichess-bot crashes resulting in the bot going offline. The python script cannot be terminated with CTRL + C anymore and I have to kill the process manually. It seems that this happens only after games have been played and not in the middle of them. I start the bot with
`virtualenv .venv -p python3`
`source .venv/bin/activate`
`python lichess-bot.py -v --logfile=bot-log.txt`
and I'll attach the last five logs.
[bot-log.txt](https://github.com/ShailChoksi/lichess-bot/files/5766530/bot-log.txt)
[bot-log2.txt](https://github.com/ShailChoksi/lichess-bot/files/5766548/bot-log2.txt)
[bot-log3.txt](https://github.com/ShailChoksi/lichess-bot/files/5766552/bot-log3.txt)
[bot-log4.txt](https://github.com/ShailChoksi/lichess-bot/files/5766554/bot-log4.txt)
[bot-log5.txt](https://github.com/ShailChoksi/lichess-bot/files/5766555/bot-log5.txt)
[bot-log6.txt](https://github.com/ShailChoksi/lichess-bot/files/5786989/bot-log6.txt)
[bot-log7.txt](https://github.com/ShailChoksi/lichess-bot/files/5829874/bot-log7.txt)

Edit: lichess-bot crashed again and I'll attach the log.
Edit 2: It now happens roughly once a day if not more often. I'll attach the (relevant) log of the very last time. There it seems to have happened after a declined bullet challenge. The logs don't show many details and I would provide more if only I knew how.

**Comment by sander-NULL** [comment]
Thanks for your answer but I don't understand how this should fix the problem. I already have lichess-bot running and it does so quite well except for the above mentioned problem. Maybe I am misunderstanding you here but how should installing lichess-bot again remedy this?

**Comment by chessBOTneeder** [comment]
This is actually not installing lichess-bot again. This is just putting your files online to repl.it and if you prefer, you might be able to let it run 24/7. You can run it online instead of on your computers cmd which can limit some code.  Just go to https://repl.it and create a new repl, then, choose a language, like "bash" and then after the repl is created, just upload your bot's files. Then run your own code for it. It probably won't crash. And like said before, you may be able to find a way to make it run 24/7 without even opening your online repl. Just Google some ways to make a repl.it repl run 24/7. **I don't know how to solve the computer cmd problem, sorry about this.**

**Comment by chessBOTneeder** [comment]
Also, If you did use repl.it, when running the code, make sure to use "shell" , not "console"

**Comment by branransom** [comment]
Hey @sander-NULL -- I was having this same issue for weeks, and couldn't figure out why. It seemed to happen both on my local computer and within an AWS EC2 instance. I cracked open the code, and eventually found that the issue was related to the queuing logic when processing commands. I have a PR open that should fix this here: https://github.com/ShailChoksi/lichess-bot/pull/253

**Comment by sander-NULL** [comment]
I have checked out your PR and it's been running since some 1.5 days without issues. So far so good :). Before running it the latest version of lichess bot also managed to run straight for a week but then crashed again unfortunately.

**Comment by branransom** [comment]
Ahh, good to hear that you haven't hit any issues with the fix. My bot has now been running for about two weeks without crashing

**Comment by sander-NULL** [comment]
Unfortunately it crashed again yesterday after running for 13 days. I don't know the exact issue but would love to provide more logs/information if only I knew how. Does anyone have an idea where to add some lines of code in order to make sure more information is logged?

**Comment by sander-NULL** [comment]
There is some more information I want to add. After lichess-bot went offline again and could not be terminated via CTRL + C I noticed that after pressing these keys lichess-bot was able to recognize the key strokes and put this in the log:
`2021-03-06 10:25:21,942: ESC[32mRecieved SIGINT. Terminating client.ESC[0m`
`2021-03-06 10:25:21,942: ESC[32mRecieved SIGINT. Terminating client.ESC[0m`
`2021-03-06 10:25:21,942: ESC[32mRecieved SIGINT. Terminating client.ESC[0m`
`2021-03-06 10:25:21,943: ESC[32mRecieved SIGINT. Terminating client.ESC[0m`
`2021-03-06 10:25:21,943: ESC[32mRecieved SIGINT. Terminating client.ESC[0m`

**Comment by sander-NULL** [comment]
Yet another info: The bot played its last game (https://lichess.org/vbaCnapk/black) last night and was still online this morning. But then at some point during the day it crashed. So **this also happens when games have not been played recently**. The log doesn't show anything. You can see the last UCI output from the last game
`2021-03-10 22:59:04,103: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> << go wtime 1340 btime 3520 winc 0 binc 0ESC[0m`
`2021-03-10 22:59:04,104: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> >> info depth 1 score cp -900 pv b3a2ESC[0m`
`2021-03-10 22:59:04,104: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> >> info depth 2 score cp -900 pv b3a2 d3c2ESC[0m`
`2021-03-10 22:59:04,104: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> >> info depth 3 score cp -900 pv b3a2 d3d2 a2b3ESC[0m`
`2021-03-10 22:59:04,104: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> >> info depth 4 score cp -900 pv b3a2 d3d2 a2b3 d2d1ESC[0m`
`2021-03-10 22:59:04,106: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> >> info depth 5 score cp -900 pv b3a2 d3d2 a2b3 d2d1 b3a2ESC[0m`
`2021-03-10 22:59:04,112: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> >> info depth 6 score cp -900 pv b3a2 d3d2 a2b3 d2d1 b3a2 d1e1ESC[0m`
`2021-03-10 22:59:04,143: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> >> info depth 7 score cp -900 pv b3a2 d3d2 a2b3 d2d1 b3a2 d1e1 a2b3ESC[0m`
`2021-03-10 22:59:04,279: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> >> bestmove b3a2ESC[0m`
`2021-03-10 22:59:04,303: ESC[32mhttps://lichess.org:443 "POST /api/bot/game/vbaCnapk/move/b3a2 HTTP/1.1" 400 47ESC[0m`
`2021-03-10 22:59:04,303: ESC[31mGiving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/vbaCnapk/move/b3a2)ESC[0m`
`2021-03-10 22:59:04,326: ESC[32mhttps://lichess.org:443 "GET /api/account/playing HTTP/1.1" 200 17ESC[0m`
`2021-03-10 22:59:04,326: ESC[94m--- https://lichess.org/vbaCnapk/black Game overESC[0m`
`2021-03-10 22:59:04,326: ESC[32m<PopenProcess at 0x7f0734139ba8 (pid=21388)> << quitESC[0m`
`2021-03-10 22:59:04,329: ESC[94m+++ Process Free. Total Queued: 0. Total Used: 0ESC[0m`

**Comment by sander-NULL** [comment]
Since this has only happened once in a couple of weeks since I switched to another computer I assume the error was rather to find on my side than on lichess-bot's. I guess I'll close this for now.
