### ISSUE TITLE
Convert SAN to UCI

### ISSUE THREAD

**Issue by selmancankurt** [ShailChoksi/lichess-bot#243]
I have a move library in my database.
I want the system to check this database first and make a move.
The move value from my database is "Nxc5".
I need to convert this move value to UCI format, or I need to take action with this move.
Can you help me?

**Comment by selmancankurt** [comment]
Code Example:

-----------------------------------------------------------------------------------------

                chess_api_data = {"fen": board.fen()}
                chess_api_res = requests.post('http://xxxx.com/db.php', data=chess_api_data)
                chess_api_result=chess_api_res.json();
                logger.info("API STATUS{} | MOVE: {}".format(chess_api_result['status'],chess_api_result['move']))

                api_move = chess_api_result['move']
                if board.is_legal(api_move ):
                    board.push(api_move )
                    logger.info("API MOVE: {}".format(api_move ))


-----------------------------------------------------------------------------------------


board.push(api_move ) <= api result value "Nxc5" but it doesn't work
how do i convert this result to UCI format

**Comment by sander-NULL** [comment]
This is not a lichess-bot problem.
You need to comply with the UCI protocol specification which you can find here: https://www.shredderchess.com/download/div/uci.zip
Here is a quote from the contained text file:
> Move format:
> ------------
> The move format is in long algebraic notation.
> A nullmove from the Engine to the GUI should be sent as 0000.
> Examples:  e2e4, e7e5, e1g1 (white short castling), e7e8q (for promotion)

**Comment by selmancankurt** [comment]
I know what the UCI format is like. I wanted to ask if there is a python code that I can convert a normal move to uci format. This is not a lichess bot problem. I'm just writing for your help.

**Comment by MarkZH** [comment]
If you are using the [python chess](https://python-chess.readthedocs.io/en/latest/) library, `board.parse_san(api_move).uci()` will get you the UCI text string. Or, you can use `board.push_san(api_move)` to use the SAN notation directly.
