### ISSUE TITLE
Visualising debug output from engine

### ISSUE THREAD

**Issue by nazrhom** [ShailChoksi/lichess-bot#244]
Hello, I am developing my own little engine and would like to hook it up to lichess, I managed to get through the setup and the bot is able to accept challenges, I am however facing some issues during the game, probably because of some issues on how I handle the UCI protocol on my end. Is there any way for me to view the UCI commands sent from lichess-bot to my engine to debug where the issues might be?

**Comment by sander-NULL** [comment]
Hi there. I don't know whether the lichess-bot supports such a function itself. But for the same reason I let my engine simply log every UCI command sent to it in a separate text file.

**Comment by nazrhom** [comment]
Thanks @sander-NULL I did the same thing and manage to get my bot up and running on lichess :)
I'll leave the issue open, maybe the maintainers of this project can shed some light on better ways to do this within lichess-bot (if any).

**Comment by MarkZH** [comment]
Using the `-v` (as in, `python lichess-bot.py -v`) option will print every message to and from lichess, including UCI commands.
