### ISSUE TITLE
File "lichess-bot.py", line 83, in start if event["type"] == "terminated":

### ISSUE THREAD

**Issue by Aujicini** [ShailChoksi/lichess-bot#245]
Does anyone have a fix for this, i have been going crazy.

**Comment by MarkZH** [comment]
What is the full error? Can you run a verbose session `python lichess-bot.py -v` and copy the output here?

**Comment by Aujicini** [comment]
The error went away, This error is being caused by Lichess. Because Lichess would refuse to respond.
