### ISSUE TITLE
Change engine for each variant

### ISSUE THREAD

**Issue by Pristar4** [ShailChoksi/lichess-bot#250]
That would allow for a more diverse Bot account

**Comment by allthatglittersisgold** [comment]
You can specify which config file to use using the --config argument. 

Alternatively you can use the Multi-variant Stockfish to play all variants.

**Comment by MarkZH** [comment]
After reviewing multiple attempts at implementing this feature, we've determined that it's much more complex that we thought. It would either require an overly complex configuration file or a set of engines that act in such an identical manner that they may as well be the same engine. So, we're closing this feature request. Thanks for the suggestion.
