### ISSUE TITLE
Python 3.7 Win10 works 3.6 did not

### ISSUE THREAD

**Issue by brianprichardson** [ShailChoksi/lichess-bot#262]
Got it to work with Python 3.7 on Win10.
With Python 3.6 noticed numerous copies of the engine exe were being created and no moves got played.
python-chess 0.24.1 should not require Python 3.7 (which started with v1.0 I think), but it enabled things to work for me, FWIW

**Comment by AttackingOrDefending** [comment]
You can add
`try:  # python version >= 3.7`
`    time.perf_counter_ns()`
`except: # python version >= 3.3`
`    time.perf_counter_ns = lambda: time.perf_counter() * 1000000000`
in line 30 of lichess-bot.py. It is crashing because time.perf_counter_ns() was introduced in python 3.7.

**Comment by brianprichardson** [comment]
Thank you.
My hunch about the why was wrong.
I just run in a 3.7 venv so it works.

Glad you are aware of it.
