### ISSUE TITLE
requirements.txt error

### ISSUE THREAD

**Issue by chessBOTneeder** [ShailChoksi/lichess-bot#275]
It appears that on ubuntu 18.04it doesn't allow me to install chess
/workspace/WhyWontItWork/lc0/lichess-bot(master)# python3 -m pip install -r requirements.txt
 Collecting certifi==2018.11.29 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting chardet==3.0.4 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna==2.8 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chess==1.4.0 (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement chess==1.4.0 (from -r requirements.txt (line 4)) (from versions: )
No matching distribution found for chess==1.4.0 (from -r requirements.txt (line 4))

**Comment by TheYoBots** [comment]
Have you made any further changes to the master repo?

**Comment by chessBOTneeder** [comment]
I haven't made any changes, except for config.yml

**Comment by TheYoBots** [comment]
Is your repo in line with https://github.com/ShailChoksi/lichess-bot ? Because python chess was just recently updated. So if you are x commits behind the master build then you will face this error.

**Comment by MarkZH** [comment]
@chessBOTneeder 

I've installed Ubuntu 18.04 on a virtual machine and I think I know what the problem is and how to solve it.

The problem is that Ubuntu 18.04 installs Python 3.6.9 when you run `sudo apt install python3`. The chess package requires Python 3.7. Please try these steps in a terminal and let me know if they work.

1. `apt install python3.7 python3.7-venv`
2. `virtualenv .venv -p python3.7`
3. `python3 -m pip install -r requirements.txt`

**Comment by MarkZH** [comment]
It might be good to add instructions for installing 3.7 for those who get the same error as the reporter.

**Comment by TheYoBots** [comment]
It has been mentioned that only python 3.7 or later is supported over [here](https://github.com/AttackingOrDefending/lichess-bot/tree/python-3.7] in the README.md, but probably something more prompt might be better.

**Comment by chessBOTneeder** [comment]
Thanks for the help! It was solved!
