### ISSUE TITLE
concurrent.futures._base.CancelledError error

### ISSUE THREAD

**Issue by AttackingOrDefending** [ShailChoksi/lichess-bot#279]
While running lichess-bot.py I randomly get an error sometimes.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\Lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\Lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\...\Lichess Bot\Tests\python chess 1.3\lichess-bot.py", line 327, in ponder_thread_func
    best_move, ponder_move = engine.search_with_ponder(board, wtime, btime, winc, binc, True)
  File "C:\Users\User\Desktop\...\Lichess Bot\Tests\python chess 1.3\engine_wrapper.py", line 95, in search_with_ponder
    return self.search(board, time_limit, ponder)
  File "C:\Users\User\Desktop\...\Lichess Bot\Tests\python chess 1.3\engine_wrapper.py", line 46, in search
    result = self.engine.play(board, time_limit, info=chess.engine.INFO_ALL, ponder=ponder)
  File "C:\Users\User\Desktop\...\LICHES~1\Tests\PYTHON~1.3\VENV~1\lib\site-packages\chess\engine.py", line 2689, in play
    return future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\Lib\concurrent\futures\_base.py", line 430, in result
    raise CancelledError()
concurrent.futures._base.CancelledError
```
It seems that lichess-bot is not crashing and just continues playing, so it doesn't cause any problem.

**Comment by MarkZH** [comment]
Does this have any affect on your engine pondering?

**Comment by AttackingOrDefending** [comment]
It happens a few moves out of book. When I print the result after a normal move I get 
`
<PlayResult at 0x1dc0430fef0 (move=e1g1, ponder=c7c5, info={'string': 'NNUE evaluation using nn-62ef826d1a6d.nnue enabled', 'depth': 24, 'seldepth': 35, 'multipv': 1, 'score': PovScore(Cp(+21), WHITE), 'wdl': PovWdl(Wdl(wins=134, draws=794, losses=72), WHITE), 'nodes': 4370009, 'nps': 776476, 'tbhits': 0, 'time': 5.628, 'pv': [Move.from_uci('e1g1'), Move.from_uci('c7c5'), Move.from_uci('e2c4'), Move.from_uci('c5d4'), Move.from_uci('e3d4'), Move.from_uci('h7h6'), Move.from_uci('a2a3'), Move.from_uci('b4d6'), Move.from_uci('c4a2'), Move.from_uci('b8c6'), Move.from_uci('f1e1'), Move.from_uci('c8d7'), Move.from_uci('f3e5'), Move.from_uci('c6e7'), Move.from_uci('d1f3'), Move.from_uci('e7f5'), Move.from_uci('c1f4'), Move.from_uci('d7c6'), Move.from_uci('e5c6'), Move.from_uci('b7c6'), Move.from_uci('f4e5'), Move.from_uci('a8b8'), Move.from_uci('a2b1'), Move.from_uci('d6e5'), Move.from_uci('d4e5'), Move.from_uci('f5h4'), Move.from_uci('f3d3'), Move.from_uci('d8d3'), Move.from_uci('b1d3')], 'hashfull': 130, 'currmove': Move.from_uci('f3g1'), 'currmovenumber': 29}, draw_offered=False, resigned=False)>
`
while after the error I get
`
<PlayResult at 0x1dc042e9f60 (move=d1e2, ponder=c7c5, info={'string': 'NNUE evaluation using nn-62ef826d1a6d.nnue enabled', 'depth': 21, 'seldepth': 33, 'multipv': 1, 'score': PovScore(Cp(+20), WHITE), 'wdl': PovWdl(Wdl(wins=130, draws=800, losses=70), WHITE), 'nodes': 894614, 'nps': 629566, 'tbhits': 0, 'time': 1.421, 'pv': [Move.from_uci('d1e2'), Move.from_uci('c7c5'), Move.from_uci('d4c5'), Move.from_uci('b4c3'), Move.from_uci('b2c3'), Move.from_uci('b6c5'), Move.from_uci('c4d3'), Move.from_uci('b8d7'), Move.from_uci('f1d1'), Move.from_uci('d8c7'), Move.from_uci('c3c4'), Move.from_uci('b7f3'), Move.from_uci('e2f3'), Move.from_uci('d7e5'), Move.from_uci('f3g3'), Move.from_uci('f8c8'), Move.from_uci('f2f3'), Move.from_uci('e5d3'), Move.from_uci('g3c7'), Move.from_uci('c8c7'), Move.from_uci('d1d3')], 'hashfull': 29}, draw_offered=False, resigned=False)>
`
I don't see any difference and it returns a ponder move, so I don't think that it affects pondering.

**Comment by AttackingOrDefending** [comment]
Turns out it was some code that I had written, that I didn't think would affect this. The error was because I started a ponder before closing the last one. Probably python-chess stops the old ponder and starts the new one because it seems that it is pondering. Sorry for opening an issue that was caused by my code.
