### ISSUE TITLE
Max and minimum time option

### ISSUE THREAD

**Issue by IT-Tl** [ShailChoksi/lichess-bot#298]
I try to tell other people who challenge my bots not to challenge 180+180 or any super long time control because 1. most don't even finish the game and 2. it wastes resources. It would be really helpful if this feature is implemented.

**Comment by amanjpro** [comment]
It is implemented, search for min and max in the default config file

**Comment by amanjpro** [comment]
https://github.com/ShailChoksi/lichess-bot/blob/132ac8b7da12b9a1d856b342cb2b9f1184332153/config.yml.default#L52-L55

**Comment by IT-Tl** [comment]
oh ok. thx for letting me know.
