### ISSUE TITLE
Bot stalls and doesn't work anymore at all.

### ISSUE THREAD

**Issue by sander-NULL** [ShailChoksi/lichess-bot#299]
Edit: Initially I thought this just happens after an aborted game. In reality though one can start a game but the bot isn't doing anything even in that first game and the logs read as shown below.

Yesterday I pulled the latest version of lichess bot. Then I started a game which worked and I quickly aborted it. After that one cannot start any games anymore.
In the logs we get:
`2021-03-22 18:05:10,151: Backing off create_engine(...) for 0.8s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-22 18:05:10,948: Backing off create_engine(...) for 2.0s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-22 18:05:12,960: Backing off create_engine(...) for 4.0s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-22 18:05:16,969: Backing off create_engine(...) for 0.9s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-22 18:05:17,836: Backing off create_engine(...) for 20.7s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-22 18:05:38,552: Backing off create_engine(...) for 59.8s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-22 18:06:38,319: Backing off create_engine(...) for 6.9s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-22 18:06:45,232: Backing off create_engine(...) for 24.0s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-22 18:07:09,276: Giving up create_engine(...) after 10 tries (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-22 18:07:09,277: Giving up play_game(...) after 6 tries (AttributeError: 'Option' object has no attribute 'is_managed')`
along with
`Traceback (most recent call last):`
`  File "/home/mi/xfame/lichess-bot/logging_pool.py", line 17, in __call__`
`    result = self.__callable(*args, **kwargs)`
`  File "/home/mi/xfame/lichess-bot/.venv/lib/python3.7/site-packages/backoff/_sync.py", line 99, in retry    `                                                                                             
`    ret = target(*args, **kwargs)`
`  File "lichess-bot.py", line 152, in play_game`
`    engine = engine_factory()`
`  File "/home/mi/xfame/lichess-bot/.venv/lib/python3.7/site-packages/backoff/_sync.py", line 99, in retry          `                                                                                       
`    ret = target(*args, **kwargs)`
`  File "/home/mi/xfame/lichess-bot/engine_wrapper.py", line 24, in create_engine`
`    options = remove_managed_options(cfg.get(engine_type + "_options", {}) or {})`
`  File "/home/mi/xfame/lichess-bot/engine_wrapper.py", line 32, in remove_managed_options`
`    return {name: value for (name, value) in config.items() if not is_managed(name)}`
`  File "/home/mi/xfame/lichess-bot/engine_wrapper.py", line 32, in <dictcomp>`
`    return {name: value for (name, value) in config.items() if not is_managed(name)}`
`  File "/home/mi/xfame/lichess-bot/engine_wrapper.py", line 30, in is_managed`
`    return chess.engine.Option(key, None, None, None, None, None).is_managed()`
`AttributeError: 'Option' object has no attribute 'is_managed'`

**Comment by AttackingOrDefending** [comment]
Lichess-bot now uses python-chess version 1.4.0. Do you have python-chess version 0.24.1? The other libraries have also been changed to a newer version.

**Comment by sander-NULL** [comment]
No I hadn't updated the libraries but I did now with `pip3 install -r requirements.txt`. Unfortunately I still get the similar errors:
`2021-03-24 14:28:46,305: --- Process Queue. Total Queued: 1. Total Used: 0`
`2021-03-24 14:28:46,305: --- Process Used. Total Queued: 0. Total Used: 1`
`2021-03-24 14:28:46,312: Starting new HTTPS connection (1): lichess.org:443`
`2021-03-24 14:28:46,385: https://lichess.org:443 "GET /api/bot/game/stream/eXQS1Fww HTTP/1.1" 200 None`
`2021-03-24 14:28:46,387: Backing off create_engine(...) for 0.6s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-24 14:28:46,956: Backing off create_engine(...) for 1.4s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-24 14:28:48,338: Backing off create_engine(...) for 0.9s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-24 14:28:49,212: Backing off create_engine(...) for 6.3s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-24 14:28:55,538: Backing off create_engine(...) for 7.5s (AttributeError: 'Option' object has no attribute 'is_managed')`
`2021-03-24 14:29:03,049: Backing off create_engine(...) for 29.4s (AttributeError: 'Option' object has no attribute 'is_managed')`

**Comment by AttackingOrDefending** [comment]
Can you delete the old venv and make a new one? I assume this error is because you still have python-chess==0.24.1 installed. The new python-chess is installed with `pip install chess==1.4.0` so you still have both. If you run `pip freeze` you should see both `chess==1.4.0` and `python-chess==0.24.1`. In python you import both using `import chess`. Although, I added `print(chess.__version__)` in lichess-bot and got 1.4.0, when I reinstalled python-chess==0.24.1 I got 0.24.1. I guess python uses the most recently install version of chess. You can also use `pip uninstall python-chess`, but this will only work if I guessed the cause of the error correctly, so I would still recommend creating a new venv.

**Comment by sander-NULL** [comment]
It does not seem that both are installed. `pip3 freeze | grep chess` gives `chess==1.4.0` and nothing else. I also deleted the old venv and followed the steps in the README.md to install lichess-bot again. I kept the old config.yml file though. It didn't help. I got the same errors.

**Comment by AttackingOrDefending** [comment]
The config.yml also changed recently but I don't know if this has anything to do with your error. You can try updating this.

**Comment by sander-NULL** [comment]
Now even renaming config.yml.default to config.yml, doing the necessary changes gives a similar but slightly different error:
`2021-03-25 11:26:31,976: Backing off create_engine(...) for 0.9s (chess.engine.EngineError: engine does not support option Move Overhead (available options: ))`
`2021-03-25 11:26:32,866: Backing off create_engine(...) for 1.8s (chess.engine.EngineError: engine does not support option Move Overhead (available options: ))`
`2021-03-25 11:26:34,706: Backing off create_engine(...) for 1.6s (chess.engine.EngineError: engine does not support option Move Overhead (available options: ))`
`2021-03-25 11:26:36,344: Backing off create_engine(...) for 5.8s (chess.engine.EngineError: engine does not support option Move Overhead (available options: ))`
`2021-03-25 11:26:42,164: Backing off create_engine(...) for 14.4s (chess.engine.EngineError: engine does not support option Move Overhead (available options: ))`
`^C2021-03-25 11:26:56,523: Backing off create_engine(...) for 23.1s (chess.engine.EngineError: engine does not support option Move Overhead (available options: ))`

**Comment by sander-NULL** [comment]
Here is the solution to the problem: In the config.yml there where uci options such as move overhead, threads and hash not commented out. Apparently lichess-bot wants the engine to support these options when set in the config.yml or it won't start the engine. So I commented those out and now it seems to work again. Is that intended behavior though?

**Comment by MarkZH** [comment]
Yes, that is the current behavior. All options in the `config.yml` file are sent to the engine in the appropriate format (UCI or Xboard). If the engine has not indicated that it accepts such an option (`option ...` for UCI engines and `feature ...` for Xboard), then an error is thrown. I don't think ignoring unsupported options is valid since we don't want to ignore options with typos in the `config.yml`. This would lead to incompletely configured engines.

**Comment by sander-NULL** [comment]
That sounds reasonable and I think we can close this issue. Thanks to all that helped and answered.
