### ISSUE TITLE
lichess-bot losing on time

### ISSUE THREAD

**Issue by sander-NULL** [ShailChoksi/lichess-bot#300]
In this game https://lichess.org/jVFc8Gvb the bot lost on time. It seems that lichess-bot didn't forward the last move played by the opponent (Qe7) to the engine. You can find the log of lichess-bot here: https://gist.github.com/sander-NULL/eae2b21fa8a7a7356a5cf20b2c21e747
The log indicates that the connection was somehow dropped.

**Comment by TheYoBots** [comment]
As I see, the bot was playing fast at the start of the game. So I assume your bot hit the rate limits. 

This was made to prevent that https://github.com/ShailChoksi/lichess-bot/pull/295

**Comment by AttackingOrDefending** [comment]
In the game the bot was taking 40 seconds per move. I don't think it hit rate limits. I think it timed out because it lost the internet connection.

**Comment by TheYoBots** [comment]
> 2021-03-27 15:52:51,598: ESC[94mBacking off api_post(...) for 0.0s (requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))ESC[0m
2021-03-27 15:52:51,628: ESC[32mStarting new HTTPS connection (2): lichess.org:443ESC[0m
2021-03-27 15:52:51,677: ESC[94mBacking off api_post(...) for 0.1s (requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))ESC[0m
2021-03-27 15:52:51,756: ESC[32mStarting new HTTPS connection (3): lichess.org:443ESC[0m
2021-03-27 15:52:52,174: ESC[32mhttps://lichess.org:443 "POST /api/bot/game/jVFc8Gvb/move/c1a3 HTTP/1.1" 200 11ESC[0m

Might be connection error too, though looking at `requests.exceptions.ConnectionError` I thought he hit the requests limit.

**Comment by sander-NULL** [comment]
> In the game the bot was taking 40 seconds per move. I don't think it hit rate limits. I think it timed out because it lost the internet connection.

Yes, the bot took a fairly long time to think between the moves so I also don't think it hit any rate limits. Maybe it did just lose the internet connection. But why didn't it reconnect at some point? After all it was a 15+15 game and I don't think there was no internet connection for that long.

**Comment by sander-NULL** [comment]
As I think it is possible that it was the internet connection I will close this for now.
