### ISSUE TITLE
Bot does not start games

### ISSUE THREAD

**Issue by sander-NULL** [ShailChoksi/lichess-bot#301]
The bot is online but when challenged it never gets to the game. One rather sees the page before with the circle moving and nothing else happens.
Here is what lichess-bot sent to what I assume was stderr: https://gist.github.com/sander-NULL/b73dc5161591222bc823e4a4d2f89ac4
Since there were no timestamps I am not sure when this exactly happened.
Also here is what was given in the log of lichess-bot starting from the last search in the last game that seems to have worked: https://gist.github.com/sander-NULL/ae178d638546500595e5c05588b21314

**Comment by TheYoBots** [comment]
If I’m right, these logs `OSError: [Errno 101] Network is unreachable` shows that you might have had a network connection error. Also you seem to be handling more than one connection at the same time. You could try restarting lichess bot locally and it might be solved if your network is good.

**Comment by sander-NULL** [comment]
> Also you seem to be handling more than one connection at the same time. You could try restarting lichess bot locally and it might be solved if your network is good.

What do you mean by more than connection? In case you mean the number of games played at a time: This is set to 1. Yes I could try to restart the bot and already did so. But this doesn't solve the issue in my opinion. If it can't connect it shouldn't throw all these errors in stderr and one should be able to play games once the bot was able to reconnect and appears to be online again.

**Comment by TheYoBots** [comment]
More than one game at a time is fine. Maybe you had something else running other that lichess-bot at the same time.

**Comment by AttackingOrDefending** [comment]
I think it was trying to establish a new connection because the network was unreachable.

**Comment by sander-NULL** [comment]
It happened again and I cannot really imagine that there is a problem with the internet connection. In any case the bot should resume its work after it could reconnect. This time it didn't come online again. Here are the logs:
https://gist.github.com/sander-NULL/0b42b8bac2392aed8f374981271b1902
https://gist.github.com/sander-NULL/9de27274a93342dd869942f0b7c6834d

**Comment by sander-NULL** [comment]
Since this has only happened once in a couple of weeks since I switched to another computer I assume the error was rather to find on my side than on lichess-bot's. I guess I'll close this for now.
