### ISSUE TITLE
429 Client Error: Too Many Requests for url: https://lichess.org/api/account/playing

### ISSUE THREAD

**Issue by OIVAS7572** [ShailChoksi/lichess-bot#309]
```
Traceback (most recent call last):
File "/logging_pool.py", line 17, in __call__
result = self.__callable(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/backoff/_sync.py", line 94, in retry
ret = target(*args, **kwargs)
File "lichess-bot.py", line 207, in play_game
if game.id not in (ongoing_game["gameId"] for ongoing_game in li.get_ongoing_games()):
File "/lichess.py", line 97, in get_ongoing_games
ongoing_games = self.api_get(ENDPOINTS["playing"])["nowPlaying"]
File "/usr/local/lib/python3.7/dist-packages/backoff/_sync.py", line 94, in retry
ret = target(*args, **kwargs)
File "/lichess.py", line 47, in api_get
response.raise_for_status()
File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 943, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://lichess.org/api/account/playing
```

I got this error for too many times

**Comment by TheYoBots** [comment]
You’ve reached the rate limit of XHR request. This is the reason why bots aren’t allowed to play ultrabullet. This can’t be prevented by any way other than by slowing down the bot. Try using #295 and increase the rate_limiting delay in your config.yml file.

**Comment by OIVAS7572** [comment]
I and this guy https://lichess.org/@/KINGNANDIultimatebot  using same big book.
I got this error while playing with him.

**Comment by TheYoBots** [comment]
It’s a XHR requests error. Why would an opening book matter. It doesn’t depend on the book it depends o how many requests are sent to lichess. And there is a limit to that number.

**Comment by OIVAS7572** [comment]
Can you say full form of XHR.
I say book means it can play about first 20 perfect moves in a fraction of second.
That will increase no of request to Lichess.
I have no problem when I play with other bots

**Comment by TheYoBots** [comment]
XHR : XMLHttpRequests

You might reach those limits depending on the speed of both bots playing or even just your. 

Again, you could make this changes https://github.com/ShailChoksi/lichess-bot/pull/295/files to your personal lichess-bot folder in your device and increase the ‘rate_limiting_delay’ in your config.yml file to prevent this.

**Comment by OIVAS7572** [comment]
ok Thanks,
I have a doubt
Is this rate_limiting_delay will add to every move or only to fast move than rate_limiting time?

**Comment by OIVAS7572** [comment]
This delay is only needed for fast moves that rate limiting time by lichess

**Comment by TheYoBots** [comment]
Every move, as I see it.
