### ISSUE TITLE
Use Python uci engine

### ISSUE THREAD

**Issue by TomMago** [ShailChoksi/lichess-bot#312]
Hello there, 

I would like use a python engine that supports uci like https://github.com/thomasahle/sunfish for example.

How can I get the bot running with such an engine?

I suppose I will have to create a executable with e.g. pyinstaller or is there a different way ?

I tried
`pyinstaller --onefile uci.py`
for the sunfish uci example, but got the error
`Backing off create_engine(...) for 4.7s (chess.engine.EngineError: engine does not support option Move Overhead (available options: ))`

Is this an issue with the engine or is my approach wrong?

Cheers
Tom

**Comment by MarkZH** [comment]
In your `config.yml` file, comment out (put a `#` at the beginning of the line) the `Move Overhead` option underneath `uci_options:` (line 26 in the `config.yml.default` file). You might also want to comment out `Threads` and `Hash` beneath it if sunfish does not support those options.

These lines in `config.yml` are options that are sent to the engine to configure it. However, the engine itself needs to indicate that it can handle these options. Sunfish made no indication that it can handle a Move Overhead option, so it was an error to try to configure it that way. If you run `lichess-bot.py` with the `-v` option, you will see all of the communication with the engine. Lines from the engine starting with `option` before a game starts shows all of the options it can handle.

**Comment by TomMago** [comment]
Hi Mark,

thanks for your answer, I got it working!

So would you say using pyinstaller is the recommended method?

**Comment by MarkZH** [comment]
If it works, I recommend it.

Another option (which I use) is to write a small scrip to `cd` into the directory that contains the engine and then run the engine from there. This allows for more flexibility in starting the program. On the sunfish website it says to use pypy or pypy3 for maximum performance, so a script would make running it that way easier.

But, again, whatever works.

**Comment by TomMago** [comment]
Ah right, i tried that, so I made a shellscript that executes the python command right?

Thats more convenient thanks!
