### ISSUE TITLE
Syzygy/Gaviota Tablebases probing

### ISSUE THREAD

**Issue by TheYoBots** [ShailChoksi/lichess-bot#314]
It would great if somehow it was possible to make use of python-chess’s feature to probe syzygy/gaviota tablebases (like how opening book was probed). This can get really handy when Engines support syzygy and gaviota tablebases can be used or vice versa and even support syzygy and gaviota probing for engines that don’t support it.

https://python-chess.readthedocs.io/en/latest/gaviota.html
https://python-chess.readthedocs.io/en/latest/syzygy.html

**Comment by MarkZH** [comment]
@TheYoBots Can you test out PR #533 that implements these tablebase lookups?

**Comment by TheYoBots** [comment]
Sure I'll have a look at it and comment.
