### ISSUE TITLE
"engine does not support option Move Overhead" using Lc0 GPU

### ISSUE THREAD

**Issue by QuantFreeman** [ShailChoksi/lichess-bot#334]
I am attempting to run a GPU version of lc0, but other than that I've followed along with the steps provided.
I'm able to launch my bot and see it on Lichess.org, however after starting a game I see the following message on console:

`2021-05-17 15:51:26,645: Backing off create_engine(...) for 0.8s (chess.engine.EngineError: engine does not support option Move Overhead (available options: WeightsFile, Backend, BackendOptions, Threads, NNCacheSize, MinibatchSize, MaxPrefetch, CPuct, CPuctBase, CPuctFactor, TwoFoldDraws, VerboseMoveStats, FpuStrategy, FpuValue, CacheHistoryLength, PolicyTemperature, MaxCollisionEvents, MaxCollisionVisits, OutOfOrderEval, MaxOutOfOrderEvalsFactor, StickyEndgames, SyzygyFastPlay, MultiPV, PerPVCounters, ScoreType, HistoryFill, MovesLeftMaxEffect, MovesLeftThreshold, MovesLeftSlope, MovesLeftConstantFactor, MovesLeftScaledFactor, MovesLeftQuadraticFactor, MaxConcurrentSearchers, DrawScoreSideToMove, DrawScoreOpponent, DrawScoreWhite, DrawScoreBlack, NodesPerSecondLimit, SolidTreeThreshold, MultiGather, TaskWorkers, MinimumProcessingWork, MinimumPickingWork, MinimumRemainingPickingWork, MinimumPerTaskProcessing, IdlingMinimumWork, ThreadIdlingThreshold, SyzygyPath, Ponder, UCI_Chess960, UCI_ShowWDL, UCI_ShowMovesLeft, ConfigFile, SmartPruningFactor, SmartPruningMinimumBatches, RamLimitMb, MoveOverheadMs, TimeManager, LogFile))`

It repeats this message several times until eventually swapping to:

`2021-05-17 15:53:26,685: Giving up create_engine(...) after 9 tries (chess.engine.EngineError: engine does not support option Move Overhead (available options: [same long list of avail. options as above]))`

My first thought is that this is due to using GPU lc0 but is there any way to work around this?

**Comment by MarkZH** [comment]
In your config.yml file, delete the line with Move Overhead under uci_options. If you get the same error with other options, delete those, too. These options are based on stockfish and may not be supported by lc0.

**Comment by MarkZH** [comment]
If you want to configure lc0, use the list printed out in the error message in your post for reference.

**Comment by ShailChoksi** [comment]
As the error message said - your "Move Overhead" option is not supported but "MoveOverheadMs" is supported

**Comment by QuantFreeman** [comment]
Thank you both! This was exactly the solution.

@ShailChoksi can I find the supported UCI options for lc0 in the documentation?
