### ISSUE TITLE
running Lc0 on windows is not working

### ISSUE THREAD

**Issue by vibranium21** [ShailChoksi/lichess-bot#345]
i wanted to test Lc0 on one of my bots and when i did python lichess-bot.py -v i got this response  that i summed up as lc0 is not compatible with these commands :|

**Comment by AttackingOrDefending** [comment]
Try using MoveOverheadMs instead of Move Overhead in the config.yml file.

**Comment by vibranium21** [comment]
oh, it worked but the leela specific settings are gone :(
