### ISSUE TITLE
'apt install python3-pip' not working in Ubuntu 21.04

### ISSUE THREAD

**Issue by Jishnu2010** [ShailChoksi/lichess-bot#349]
So I tried to create a bot in Ubuntu 21.04. The readme document says that we need to install pip using `apt install python3-pip` but when I do it I get the following output:
```
ubuntu@ubuntu:~/lichess-bot-master$ apt install python3-pip
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```
So I tried with sudo and got the following result:
```
ubuntu@ubuntu:~/lichess-bot-master$ sudo apt install python3-pip
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-pip' has no installation candidate
```
I think I should add some additional information:
1. I didn't install python. It was already installed.
2. The previous steps have been done correctly.
3. Also, the python version is 3.9.4. I checked it with python3 --version.

Please check why this is happening. Thanks.

**Comment by MarkZH** [comment]
Try running `sudo apt update` and then retry `sudo apt install python3-pip`. The update command gets the latest list of packages from Ubuntu. You might also want to run `sudo apt upgrade` after the update to make sure all your other software is up to date.

**Comment by Jishnu2010** [comment]
Well I tried it but its not working. Same problem.

**Comment by MarkZH** [comment]
Maybe there's a repository that needs enabling on your computer. [This answer](https://stackoverflow.com/a/52394612/2156537) might work:

```bash
sudo add-apt-repository universe
sudo apt update
sudo apt install python3-pip
```

You can also look in `/etc/apt/sources.list` to check if the universe repository is enabled (not commented out).

**Comment by Jishnu2010** [comment]
Thanks very much for the quick answer. I have finally installed pip and it is working. Also python got updated from 3.9.4 to 3.9.5, likely as a result of the 'universe'. I am closing this issue.
