### ISSUE TITLE
error while trying to run the bot 

### ISSUE THREAD

**Issue by LuciusSomberlas** [ShailChoksi/lichess-bot#350]
am running linux deepin 20.2
![Screenshot_select-area_20210605234918](https://user-images.githubusercontent.com/82325074/120905178-ff71c580-c658-11eb-9420-4501404c00f8.png)
![Screenshot_select-area_20210605235002](https://user-images.githubusercontent.com/82325074/120905180-03054c80-c659-11eb-938c-0f2488ff7cd3.png)

**Comment by ShailChoksi** [comment]
There is an extra `-` after your book in the config file.
Remove that line and i believe it should work

**Comment by LuciusSomberlas** [comment]
thank you
