### ISSUE TITLE
Python Engine importing files

### ISSUE THREAD

**Issue by Varsius** [ShailChoksi/lichess-bot#351]
Platform: Windows 10
Protocol: UCI

I wrote a chess engine in python and compiled it with PyInstaller to a single .exe file (using the --onefile flag).
The engine works just fine when I execute the .exe file or test it with Arena Chess GUI.
Unfortunately the lichess bot gives me the following error:
`Backing off play_game(...) for 0.6s (chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1))`
The error occurs everytime I try to use my own opening book. Therefore it has to be a problem with importing an extra file. (Yes I know you can use opening books via the config, but I want to implement endgame databases in a later state where I would have the same problem.)
I tried using the following lines to import my opening book, but I had no succes:
`reader = chess.polyglot.open_reader("Perfect2017.bin")`
`reader = chess.polyglot.open_reader("./Perfect2017.bin")`
`reader = chess.polyglot.open_reader(os.path.abspath("Perfect2017.bin"))`

Can somebody tell me how to import files when using this lichess api? It should be possible, because afaik LC0 also depends on weights saved as an extra file for example.

Is there a place where I can see the error message why my engine crashed?

I also tried using the "info string sometext" command, but it did not seem to work, I did not see any text in my console where I was running the lichess.bot.py -u command.

I would really appreciate your help

**Comment by MarkZH** [comment]
How do you tell your engine to open the book? Hard-coded path in your code? Command line option?

Where is the book file (`Perfect2017.bin`) located? If it is in the same directory as the engine, try copying it into the lichess-bot folder or giving the full path to where it is actually stored. When you start `lichess-bot.py`, the active directory is the lichess-bot directory, so your engine will look for the book file there.

If that doesn't work, try running lichess-bot with the `-v` option (`python lichess-bot.py -v`) to enable verbose output.

**Comment by Varsius** [comment]
The book was located in the same directory as the engine. Moving the book in the lichess-bot folder or adding "./engines" to the path did solve my problem. 

The hint with the working directory was just what I needed, thanks a lot @MarkZH!
Maybe it could be documented somethere that the working directory is not the engines folder (or I overlooked where to find this information).

**Comment by MarkZH** [comment]
I added a section to the README file.
