### ISSUE TITLE
Python Engine printing from thread

### ISSUE THREAD

**Issue by Varsius** [ShailChoksi/lichess-bot#368]
I wrote an engine in python which worked just fine with the lichess-bot. Now I put my search function in a separate thread in order to allow pondering and the stop command to work. Unfortunately, the print commands from the thread are not recognized by the lichess-bot. With the verbose output I can for example see the answers to the uci command (id name ... etc.) coming from the main program but not any best move commands coming from the thread with the search function.
When I execute my engine manually and enter the same uci commands as seen in the verbose output, the engine works normally and I can see every answer from the engine.

Is there a way to print from a thread?
I also tried `sys.stdout.write()` which made no difference.

Thanks for your help,
Valentin

**Comment by MarkZH** [comment]
This might be a buffering issue--that is, when your program is not run in interactive mode, the output of `print()` is stored in a buffer until some time in the future. Try using the `flush` keyword argument to force immediate output.

Something like: `print('bestmove', best_move_found, 'ponder', pondering_move, flush=True)`.

**Comment by Varsius** [comment]
Using `flush=True` works great, thanks a lot for your help!
