### ISSUE TITLE
Allow to specify supported time controls in exact time

### ISSUE THREAD

**Issue by mr-yt12** [ShailChoksi/lichess-bot#37]
Now we can allow "bullet", "ultrabullet", etc. But would be nice to be able to set it to < 1+1, for example.

**Comment by ddugovic** [comment]
IMHO FICS-style formulas would be ideal (but also the most work to implement).

**Comment by ornicar** [comment]
What does `< 1+1` mean? Does it include `0+2`?

What does `<5+8` mean?

**Comment by ddugovic** [comment]
I've used formulas of this form (this is much more advanced than I reasonably expect to be supported):

```
f1: rated && (base + 2 * inc / 3 < 5) && !computer && rd <= 80 # rated versus human opponents
f2: base == 1 && inc <= 1 && !suicide # casual play
formula: f1 || f2
```

**Comment by Aspiration-to-Stars** [comment]
<(1+1) = <(1 minute 40 seconds). It includes 0+2, but not 2+0. <(5+8) = <(10 minutes 20 seconds). I think Lichess uses a similar formula to place challenges on the Graph.

**Comment by tttony** [comment]
We can create an option to only play with increment > 0 or = 1
Other option to accept matches with <= 60 seconds, I refer to set it with seconds 1+1 it's confusing
The engine will only accept matches with <= 60 + 1 seconds

**Comment by quillford** [comment]
PR #132 adds a max increment setting

**Comment by MarkZH** [comment]
PR #255 adds a min and max base time for games.  With #132, the functionality described in this issue is implemented (not in the same way described by the OP, but I believe it is close enough).
