### ISSUE TITLE
Bot doesnt make move

### ISSUE THREAD

**Issue by galacticue06** [ShailChoksi/lichess-bot#374]
I'm currently trying to run Sunfish's slightly modified version, and it doesn't seem to  work. When I start it in verbose logging mode it outputs:

> 2021-07-19 16:08:25,031: Starting new HTTPS connection (1): lichess.org:443
> 2021-07-19 16:08:25,282: https://lichess.org:443 "GET /api/account HTTP/1.1" 200 None
> 2021-07-19 16:08:25,282: Welcome Sunfish-NNUE!
> 2021-07-19 16:08:25,283: You're now connected to https://lichess.org/ and awaiting challenges.
> 2021-07-19 16:08:25,983: Something went wrong. Game is starting and we don't have a queued process
> 2021-07-19 16:08:25,983: --- Process Used. Total Queued: 0. Total Used: 1

I have tried to use the engine with CuteChess and it runs flawlessly. What can I be missing? 

Thanks in advance.

**Comment by AttackingOrDefending** [comment]
You may be able to find the solution [here](https://github.com/ShailChoksi/lichess-bot/issues/312) or you can adapt sunfish to run with homemade engines.

**Comment by galacticue06** [comment]
Compiled it but I still couldn't get it work. It prompts "AttributeError: 'Option' object has no attribute 'is_managed'" continuesly for some reason.

**Comment by MarkZH** [comment]
You might have an old version of python-chess. Try running `pip install -r requirements.txt` to install the latest versions of all dependencies.

**Comment by MarkZH** [comment]
@galacticue06 Were you able to get your bot to work?
