### ISSUE TITLE
Search time for first move in config.yml

### ISSUE THREAD

**Issue by sander-NULL** [ShailChoksi/lichess-bot#378]
Is there an option in the config.yml for the search time of the first move I am not seeing? Until now I had to edit that in the lichess-bot.py. If there is no such option in the config.yml this should be considered a feature request :),

**Comment by MarkZH** [comment]
There's no configuration for changing the first move time. It's hard coded [here](https://github.com/ShailChoksi/lichess-bot/blob/a79094704270f09b92d8653eafb4e41f001aa209/lichess-bot.py#L322). Out of curiosity, why do you want to change it?

**Comment by sander-NULL** [comment]
Because people playing the engine tend to abort games more often when it is set to 10sec. I assume they think the engine is hanging and won't start the game. I usually set to to 3sec instead.
