### ISSUE TITLE
Does not accept rematches

### ISSUE THREAD

**Issue by SquarishRectangle** [ShailChoksi/lichess-bot#379]
On top of that, when a rematch is requested, a process is taken up even though the game isn't started. The process does get freed up after 30 seconds when it "aborts" the nonexistent game but it's still super annoying. 

Edit: As of now stopped "aborting" and the process is taken up forever until I restart lichess-bot.

**Comment by Impossibum** [comment]
duplicate issue #376

**Comment by MarkZH** [comment]
The problem seems to have been [fixed on the lichess site](https://github.com/ornicar/lila/commit/47e438f19b299a3512ecf303bb7317d8ab810375). Please check to see if the problem is solved.

**Comment by SquarishRectangle** [comment]
Yes, this issue has been resolved.
