### ISSUE TITLE
Incomplete URL

### ISSUE THREAD

**Issue by SquarishRectangle** [ShailChoksi/lichess-bot#380]
Lichess has recently been assigning URLs of more than 8 characters which gives this lovely error. 
Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/w0uW0e94/chat)
The correct URL was https://lichess.org/api/bot/game/w0uW0e94kO9d/chat which is 12 characters
Lichess-bot seems incapable of handling URL strings of more than 8 characters

**Comment by MarkZH** [comment]
I don't see your error when my bot posts messages to chat. When does your error occur?

---

As for the length of game IDs, I don't think that's the problem. It's not that lichess-bot cannot handle the longer game IDs; lichess.org does not send the longer game IDs through the API. Here are the JSON messages received for a recent game with my bot (notice that both JSON messages have 8-character IDs):

Challenge:

    {'type': 'challenge', 'challenge': {'id': 'zvrKic1M', 'url': 'https://lichess.org/zvrKic1M', 'status': 'created', 'challenger': {'id': 'johnny_adroit', 'name': 'Johnny_Adroit', 'title': None, 'rating': 1317, 'provisional': True, 'online': True, 'lag': 3}, 'destUser': {'id': 'genetic_chess_bot', 'name': 'Genetic_Chess_Bot', 'title': 'BOT', 'rating': 1697, 'online': True}, 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'rated': False, 'speed': 'bullet', 'timeControl': {'type': 'clock', 'limit': 120, 'increment': 0, 'show': '2+0'}, 'color': 'random', 'perf': {'icon': '\ue047', 'name': 'Bullet'}}}

Game start:

    {'type': 'gameStart', 'game': {'id': 'zvrKic1M', 'source': 'friend'}}

The full game ID from the lichess site is zvrKic1M4TsY, but this shortened ID seems to work just as well as the longer one. Both https://lichess.org/zvrKic1M4TsY and https://lichess.org/zvrKic1M go to the same game (although the views are different).

**Comment by SquarishRectangle** [comment]
This issue was completely my fault. I was looking back to an older project and it was still using a very old version of lichess-bot. This went away after I updated it.
