### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by sander-NULL** [ShailChoksi/lichess-bot#383]
Same issue as https://github.com/ShailChoksi/lichess-bot/issues/381
It worked for a while and definitely happened less often than before but is still happening sometimes. The end of the log was
`2021-08-14 03:00:35,925:   Resetting dropped connection: lichess.org`
`2021-08-14 03:00:36,041:   https://lichess.org:443 "POST /api/challenge/73zjsAyd/decline HTTP/1.1" 200 11`                             
`2021-08-14 03:00:36,042:   Decline Chess960 rated challenge from peepchuy(1179) for reason 'variant'`

**Comment by MarkZH** [comment]
How do you know it won't accept challenges? What happens when you challenge the bot?

**Comment by sander-NULL** [comment]
After nearly two days without any games played I tried challenging it myself. In my browser it stays at the page where we have the circle moving indicating that the game is being set up and about to start. But it never gets there and instead loads forever.

**Comment by MarkZH** [comment]
Can you copy the last queue line from your logs when the problem occurs? It's the one that looks like this:

2021-07-30 05:24:25,623: --- Process Queue. Total Queued: 1. Total Used: 0

**Comment by sander-NULL** [comment]
Hmm I didn't save the log. But I will write the log to file from now on again and will post it when the problem occurs again.

**Comment by MarkZH** [comment]
Does your bot work now?
