### ISSUE TITLE
Zappa Mexico II no longer works

### ISSUE THREAD

**Issue by inversed-ru** [ShailChoksi/lichess-bot#388]
I used to run a Zappa Mexico II bot on Lichess, but sadly it no longer works. After starting a game I get the following error in the console:
`Backing off create_engine(...) for 0.1s (chess.engine.EngineError: unknown option type: '')`
Changing the uci_options in the config or even removing the entire section has no effect. Stockfish seems to work without issues.

**Comment by MarkZH** [comment]
2021-08-27 22:41:43,588: <UciProtocol (pid=7704)>: >> option name Singular Extension Min Depth default 4 min 4 max 100

This option is missing a `type` field. Somewhere in this line there should be a `type spin`. This is a bug in the engine.

**Comment by MarkZH** [comment]
Unless you can get the source code to the Zappa engine, here's something you can try. In the lichess-bot directory, open `.venv\Lib\site-packages\chess\engine.py` (the `.venv` directory may be different depending on what you typed when running `virtualenv` when you set up lichess-bot). Just above the line 291 (`raise EngineError(f"unknown option type: {self.type!r}")`), add the line `return int(value)`. The code starting from line 290 should look like this:

        else:
            return int(value)
            raise EngineError(f"unknown option type: {self.type!r}")

Let me know if this gets your bot working.

**Comment by MarkZH** [comment]
The main problem with the above fix is that it will have to be repeated every time python-chess gets upgraded when a new version of lichess-bot is released.

**Comment by inversed-ru** [comment]
@MarkZH Thanks a lot, the fix helped!
