### ISSUE TITLE
chess.xboard library missing

### ISSUE THREAD

**Issue by DrSava04** [ShailChoksi/lichess-bot#389]
upon attempting to run the bot using `python lichess-bot.py` I get the error

`Traceback (most recent call last):
  File "C:\Users\savai\Desktop\lichess-bot-1.1.3\lichess-bot.py", line 5, in <module>
    import engine_wrapper
  File "C:\Users\savai\Desktop\lichess-bot-1.1.3\engine_wrapper.py", line 3, in <module>
    import chess.xboard
ModuleNotFoundError: No module named 'chess.xboard'`

Any idea why or how to fix it?

**Comment by MarkZH** [comment]
It looks like you have an old version of lichess-bot. Try running `git pull` followed by `python3 -m pip install -r requirements.txt`

**Comment by DrSava04** [comment]
Hello,
Thanks for responding to my issue

I have successfully updated the version of lichess-bot that I was using.

However, running the `.\.venv\Scripts\activate` results in the following error:
`\.venv\Scripts\activate : The term '\.venv\Scripts\activate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ \.venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\.venv\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

Furthermore, running the bot now results in a different error:
`Traceback (most recent call last):
  File "C:\Users\savai\Desktop\lichess-bot-1.1.3\lichess-bot.py", line 5, in <module>
    import engine_wrapper
  File "C:\Users\savai\Desktop\lichess-bot-1.1.3\engine_wrapper.py", line 3, in <module>
    import chess.xboard
  File "C:\Users\savai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\chess\xboard.py", line 25, in <module>
    from chess.engine import EngineTerminatedException
ImportError: cannot import name 'EngineTerminatedException' from 'chess.engine' (C:\Users\savai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\chess\engine.py)`

**Comment by MarkZH** [comment]
What commands do you normally run to start lichess-bot? What do you run before `python lichess-bot.py` to enter the virtual environment? The `.venv` might be the wrong directory depending on your setup.

**Comment by DrSava04** [comment]
I appologize for my previous post. I made a small mistake in the way I ran the bot. It all seems to work now, thank you for your help!

**Comment by MarkZH** [comment]
Good to hear. Close this issue once you get your bot working.
