### ISSUE TITLE
KeyError when playing King of the Hill variant

### ISSUE THREAD

**Issue by IamMusavaRibica** [ShailChoksi/lichess-bot#393]
I'm using lichess-bot with Fairy-Stockfish engine (https://github.com/ianfab/Fairy-Stockfish)
Starting a King of the Hill game leads to a KeyError and therefore not making any moves:
`Backing off play_game(...) for 4.0s (KeyError: 'wdraw')`
![image](https://user-images.githubusercontent.com/65848142/134579706-6cb667ee-9114-4334-a46f-bced29252d48.png)

**Comment by MarkZH** [comment]
This will be fixed by PR #391.

**Comment by MarkZH** [comment]
Until the fix is merged, you can make the change yourself. See https://github.com/ShailChoksi/lichess-bot/pull/391/files

In line 384 or lichess-bot.py, change

    return game.state[f'{game.opponent_color[0]}draw']

to 

    return game.state.get(f'{game.opponent_color[0]}draw', False)

**Comment by MarkZH** [comment]
After doing a `git pull`, is the problem fixed now?

**Comment by TG-KRISH** [comment]
N0 not that just rewrite the starting code it will be fine

**Comment by IamMusavaRibica** [comment]
Success. Thanks!

pet, 24. ruj 2021. u 01:39 Mark Harrison ***@***.***> napisao
je:

**Comment by MarkZH** [comment]
Great! Close this issue if the bug is fixed.
