### ISSUE TITLE
Wasn't able to install the python-chess library

### ISSUE THREAD

**Issue by CalKK8** [ShailChoksi/lichess-bot#394]
Hi, I was recently trying to use python on Ubuntu 18.04 to install the python-chess library with the command `python3 -m pip install -r requirements.txt`, but this is the output it produces:

```
Collecting certifi==2021.5.30
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting chardet==4.0.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna==3.2
  Using cached idna-3.2-py3-none-any.whl (59 kB)
ERROR: Could not find a version that satisfies the requirement chess==1.6.1 (from versions: none)
ERROR: No matching distribution found for chess==1.6.1
```

**Comment by CalKK8** [comment]
As a sidenote, I'm also using Python 3.6.9.

**Comment by MarkZH** [comment]
The python-chess library requires python 3.7, which is a separate install in Ubuntu: `sudo apt install python3.7`. You may need to activate the `universe` repository to get it.
