### ISSUE TITLE
UCI Engine Error with Stockfish dev

### ISSUE THREAD

**Issue by TheYoBots** [ShailChoksi/lichess-bot#402]
I'm running Stockfish latest dev ([link to file](https://abrok.eu/stockfish/latest/linux/stockfish_x64_modern.zip)) and recieve a UCI related error. Below are the logs when I run `python3 lichess-bot.py -v`.

```
  Accept Bullet casual challenge from YohaanSethNathan(1078)
  Resetting dropped connection: lichess.org
  https://lichess.org:443 "POST /api/challenge/Oq3BejmF/accept HTTP/1.1" 200 11
  --- Process Queue. Total Queued: 1. Total Used: 0
  --- Process Used. Total Queued: 0. Total Used: 1
  Starting new HTTPS connection (1): lichess.org:443
  https://lichess.org:443 "GET /api/bot/game/stream/Oq3BejmF HTTP/1.1" 200 None
  Using selector: EpollSelector
  Using PollingChildWatcher
  <UciProtocol (pid=57)>: Connection made
  <UciProtocol (pid=57)>: Process exited
  <UciProtocol (pid=57)>: << uci
  <UciProtocol (pid=57)>: Connection lost (exit code: 1, error: None)
  Backing off create_engine(...) for 0.3s (chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1))
  Using selector: EpollSelector
  Using PollingChildWatcher
  <UciProtocol (pid=59)>: Connection made
  <UciProtocol (pid=59)>: Process exited
  <UciProtocol (pid=59)>: << uci
  <UciProtocol (pid=59)>: Connection lost (exit code: 1, error: None)
  Backing off create_engine(...) for 1.9s (chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1))
```

The above occurs on and on.

**Comment by TheYoBots** [comment]
Might be similar to #387.

**Comment by MarkZH** [comment]
When I try to run that stockfish in a terminal, I get the error

    ./stockfish_21121115_x64_modern: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by ./stockfish_21121115_x64_modern)

Do you get the same error when running this stockfish by itself?

**Comment by TheYoBots** [comment]
Yes I do face the same error when I run stockfish in a terminal. Might be out of context, but how to you upgrade to glibc 2.34?

**Comment by MarkZH** [comment]
That depends on your system. it is installed in [Impish Indri, the latest version of Ubuntu](https://launchpad.net/ubuntu/+source/glibc). If you run Arch Linux or a variant, you can install it using the [AUR](https://aur.archlinux.org/). Although, since glibc 2.34 was only released six months ago, it will probably soon be updated in the official repositories of most Linux distros if it hasn't already.

**Comment by MarkZH** [comment]
Since this doesn't involve lichess-bot, please close this issue.
