### ISSUE TITLE
Games end with `400 Client Error` for UCI Bots

### ISSUE THREAD

**Issue by TheYoBots** [ShailChoksi/lichess-bot#411]
At the end of each game an error occurs (in relation Draw Offering) `Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/gGXh05ih/move/e4e5?offeringDraw=false)` as seen below when `python3 lichess-bot.py -u` is used to start the bot:

```
move: 49
Searching for wtime 0 btime 1120
depth: 3
nps: 77000
nodes: 77
score: PovScore(Cp(+1226), WHITE)
Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/gGXh05ih/move/e4e5?offeringDraw=false)
--- https://lichess.org/gGXh05ih/white Game over
+++ Process Free. Total Queued: 0. Total Used: 0
```

These are the logs I get when I run `python3 lichess-bot.py -v`:
```
<UciProtocol (pid=72)>: >> info depth 14 seldepth 26 multipv 1 score cp 1553 nodes 394641 nps 1157304 tbhits 0 time 341 pv g3f4 g1f1 f2f3 f1h1 h4h5 g7f8 h5h6 f8e7 g4g5 h1d1 f4g4 e7f7 g5g6 f7f8 g4f5 f8e7 g6g7 e7f7
https://lichess.org:443 "POST /api/bot/game/0uojtTZ4/move/a3a6?offeringDraw=false HTTP/1.1" 400 43
Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/0uojtTZ4/move/a3a6?offeringDraw=false)
https://lichess.org:443 "GET /api/account/playing HTTP/1.1" 200 17
<UciProtocol (pid=72)>: << stop
<UciProtocol (pid=72)>: << quit
<UciProtocol (pid=72)>: >> info depth 15 seldepth 24 multipv 1 score cp 1530 nodes 644271 nps 1158760 tbhits 0 time 556 pv g3f4
<UciProtocol (pid=72)>: >> bestmove g3f4 ponder g1b1
<UciProtocol (pid=72)>: >> info depth 14 seldepth 19 multipv 1 score cp 1211 nodes 130763 nps 983180 tbhits 0 time 133 pv a3a6 d4d8 g4g5 d8d5 g3g4 d5d8 h4h5 g7f8 a6a7 f8g8 f2f4 g8f8 h5h6 f8g8 g5g6 d8c8
<UciProtocol (pid=72)>: >> info depth 15 seldepth 20 multipv 1 score cp 1179 nodes 261951 nps 1003643 tbhits 0 time 261 pv a3a6 d4d3 f2f3 d3d1 g4g5 d1g1 g3f4 g1h1 f4g4 h1g1 g4f5 g1f1 f3f4 f1h1 h4h5 h1h5 a6h6 h5h6 g5h6 g7g8 f5f6
<UciProtocol (pid=72)>: Process exited
<UciProtocol (pid=72)>: Connection lost (exit code: 0, error: None)
--- https://lichess.org/0uojtTZ4/white Game over
+++ Process Free. Total Queued: 0. Total Used: 0
```
I'm not sure if this error occurs even with XBoard bots, but it does ocuurs with Bots running under the UCI protocol. Also this error doesn't effect the bot. Once a new game starts it plays the game, but at the end of each game this error occurs.

**Comment by MarkZH** [comment]
Both games ended with your bot running out of time. I think, since the game was over, the URL for submitting moves became invalid, which caused the error.

**Comment by MarkZH** [comment]
Does this happen with games that don't end in time forfeits?

**Comment by TheYoBots** [comment]
> Does this happen with games that don't end in time forfeits?

No it doesn't and your previous answer was right, but Losing/Winning a game on time shouldn't be an error. Is there a way the bot can detect when the time reaches zero for either the opponent or the bot and stop?

**Comment by MarkZH** [comment]
Since the official game clock is on the lichess server, the only way to know when time is expired is to try to submit a move. Trying to detect a time out ahead of time would risk giving up a game when there is still officially time left, and querying the servers for the game time before submitting a move wastes time that could be used to submit a move. I think this error needs to be reported to the [lichess repository](https://github.com/ornicar/lila).

**Comment by MarkZH** [comment]
I've created PR #429 to address this issue. Let me know if it works for you.

**Comment by TheYoBots** [comment]
> I've created PR #429 to address this issue. Let me know if it works for you.

Thanks! It works. Just that now at the start of each game I recieve this error:
```
Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/api/challenge/OUIGGpGV/accept)
```

My bot was the one that challenged the opponent and the opponent accepted the challenge. I don't really think that this error is because of the edit you made though.

**Comment by MarkZH** [comment]
Does this happen every game? If both your bot and the opponent accept the challenge, does the game still get played?

**Comment by TheYoBots** [comment]
In my logs it shows that in drawn games I still get the same 400 Client Error: https://lichess.org/9f6ZyQ8mLmKJ
```
Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/9f6ZyQ8m/move/g6h6?offeringDraw=false)
```
Regarding your question:
> Does this happen every game? If both your bot and the opponent accept the challenge, does the game still get played?

It doesn't happen when I challenge the AI. It happens when I challenge another BOT/lichess user. It doesn't happen when another user(bot or human) challenges the BOT. 

Basically it happens only when the BOT challenges another user/bot or when my bot requests for a rematch:
```
 Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/api/challenge/Kkbubdaa/accept)
 Skip missing Bullet casual challenge from BOT YoBot_v2(2643)
```

**Comment by MarkZH** [comment]
I don't think I can do anything about the end-of-game `api_post()` error since that error is sent by lichess. I don't want to hide that error in case other important errors get hidden.

The error that happens when your bot challenges someone else probably means the challenge was declined. At least, that what it means for my bot.

The change in the linked PR only ensures that an error in `api_post()` does not prevent getting all messages from lichess.

**Comment by TheYoBots** [comment]
I face the issue when the opponent accepts the challenge/rematch. Not sure about when the challenge/rematch is declined.

**Comment by MarkZH** [comment]
That sounds like a bug in the lichess site, similar to [this one](https://github.com/lichess-org/lila/issues/9515). You might want to report it there.

**Comment by MarkZH** [comment]
I've added another commit to #429 to only show those error messages when running with `-v`. Let me know if it works well.
