### ISSUE TITLE
Bot is not responding to eval command if it is sent during the opponent's move.

### ISSUE THREAD

**Issue by uwuplant** [ShailChoksi/lichess-bot#417]
On [both](https://lichess.org/@/AMemeBot/all) of my [bots](https://lichess.org/@/IUseStockfish), the eval command is not being recognized during my opponent's move after the recent bot changes from the last few days.

Steps to reproduce:
1. Start a game with any player.
2. Run the !eval command in spectator chat during the opponent's turn.
3. No response will be given.
4. Run the !eval command during your bot's turn.
5. You should get a response this time.

Intended behavior:
Bot should always respond to !eval, not only during your turn.

**Comment by AttackingOrDefending** [comment]
It was caused by #340. I will make a PR with a fix in about 2 hours.

**Comment by AttackingOrDefending** [comment]
@uwuplant Can you test with the branch https://github.com/AttackingOrDefending/lichess-bot/tree/fix-ponderpv-bug?

**Comment by uwuplant** [comment]
Works fine now, thank you!
