### ISSUE TITLE
`offer_draw` doesn't work with `online_egtb`

### ISSUE THREAD

**Issue by Torom** [ShailChoksi/lichess-bot#421]
Hi,
first of all, I really like the offer draw feature. I think you should release a new version and enable it by default so that as many as possible use the function.

However, it has no function when `online_egtb` is enabled. I think also egtb moves that are known to be draws should be counted as 0.00 moves, so that the bot can still offer and accept draws.

**Comment by AttackingOrDefending** [comment]
Can you test #422?

**Comment by Torom** [comment]
After a short test it seems to work. The bot offers a draw when it gets online egtb moves.

There was a strange loss on time, though it should have nothing to do with the change, there were still well over 7 pieces on the board.

**Comment by MarkZH** [comment]
Hi @Torom. We made some changes to #422--namely: only a wdl score of zero results in a draw offer and -2 results in a resignation. Could you test this? Let us know if losing on time is still a problem.

**Comment by Torom** [comment]
Tested it a few rounds and everything looks good.
