### ISSUE TITLE
Bot becomes unresponsive

### ISSUE THREAD

**Issue by Torom** [ShailChoksi/lichess-bot#427]
The bot becomes unresponsive to challenges after a certain time. Immediately after the start everything is fine, but after a certain time it no longer responds to challenges and does not display them. I can't say if this happens after ten minutes or an hour.

I'm pretty sure this problem is related to #424. Once I reverted this commit the problem did not occur.

**Comment by MarkZH** [comment]
Some steps to help us out:

1. Please post your config.yml file. Delete the `token` field before posting. If you paste it directly here, put three backticks (```) above and below to preserve indentation.
2. Run lichess-bot in verbose mode with `-v` and copy the last lines before it becomes unresponsive here.
3. If there's nothing interesting in the verbose log, try putting `logger.debug(event)` below [line 130 in `lichess_bot.py`](https://github.com/ShailChoksi/lichess-bot/blob/e8a452705b0574b0853b4814e08e9a5a818c3045/lichess-bot.py#L130). After the edit, run with verbose logging again.

**Comment by MarkZH** [comment]
Also, does this happen only when your bot plays correspondence games? Or, does it happen even when it's only standard clocked games?

**Comment by MarkZH** [comment]
I think I found the problem. Can you try PR #428 solves the problem?

**Comment by Torom** [comment]
I have tested your PR and with it the bot runs fine. Thanks for the quick fix.
