### ISSUE TITLE
2 Move overhead 

### ISSUE THREAD

**Issue by iamhajemi** [ShailChoksi/lichess-bot#431]
In config.yml file there is 2 move overhead option. What is the difference between them?

**Comment by TheYoBots** [comment]
`move_overhead` is managed by lichess-bot and `Move Overhead` is managed by the engine you use with lichess-bot. If the engine you use doesn't support the uci option `Move Overhead` then it can be removed. The options under `uci_options:` is just a template of options, it can be changed to your desire.

**Comment by iamhajemi** [comment]
> `move_overhead` is managed by lichess-bot and `Move Overhead` is managed by the engine you use with lichess-bot. If the engine you use doesn't support the uci option `Move Overhead` then it can be removed. The options under `uci_options:` is just a template of options, it can be changed to your desire.

**Comment by iamhajemi** [comment]
> `move_overhead` is managed by lichess-bot and `Move Overhead` is managed by the engine you use with lichess-bot. If the engine you use doesn't support the uci option `Move Overhead` then it can be removed. The options under `uci_options:` is just a template of options, it can be changed to your desire.

If I set Move Overhead 1000 and move_overhead to 0 is it eqaul if I set Move Overhead 0 and move_overhead 0?

**Comment by AttackingOrDefending** [comment]
No. You can think of Move Overhead as subtracting from your increment and move_overhead as subtracting from your time.

For example:
Move Overhead = 100
move_overhead = 2000
bot_time = 40000 - move_overhead = 40000 - 2000 = 38000
bot_increment = 1000 - Move Overhead = 1000 - 100 = 900

**Comment by MarkZH** [comment]
Also, Move Overhead can have different effects on different engines depending on how they are programmed (assuming the engine supports that option, which Leela does not). The move_overhead option always has the same effect because lichess-bot handles that option in the way @AttackingOrDefending described above.
