### ISSUE TITLE
Instamove blunder after pondermiss

### ISSUE THREAD

**Issue by uwuplant** [ShailChoksi/lichess-bot#432]
I recently encountered a (possibly engine-related) bug where after a ponder miss, my bot will sometimes make a depth 1 instamove, potentially losing the game from one move.
Example:
![image](https://user-images.githubusercontent.com/26153075/151670410-33f471be-9b1b-4d5a-b13e-3e01310f6f1f.png)

I'm not sure if this is necessarily an issue with lichess-bot itself, or just a weird engine "this will just happen once in a while" thing. Feel free to close this if it is not related to this.

**Comment by MarkZH** [comment]
Does this happen with other chess interfaces (CuteChess, Winboard, etc.)?

**Comment by MarkZH** [comment]
Also, just as a sanity check, what was the previous `go ponder` command prior to the screenshot?

You can also capture the entire log to a file by passing the option `--logfile log.txt` to lichess-bot.

**Comment by uwuplant** [comment]
I'll try to find another instance of it happening and send full logs of that. 
I found a few more instances from my bot's game history.
https://lichess.org/tDd8nanj/black
https://lichess.org/9L0BfUFBD3V1
https://lichess.org/xm26PYyn/white#160

**Comment by uwuplant** [comment]
Got one! 
[full_log.txt](https://github.com/ShailChoksi/lichess-bot/files/7965095/full_log.txt)

https://lichess.org/oCd5Tynv/white#199

**Comment by MarkZH** [comment]
> Got one! [full_log.txt](https://github.com/ShailChoksi/lichess-bot/files/7965095/full_log.txt)
> 
> https://lichess.org/oCd5Tynv/white#199

I don't see anything strange in this log except for the instamove happening three times: move 75, move 86, and move 100. Search the log for "depth 0" to find them. The only commonality I see is that they occur after ponder misses, but only seldomly.

Let's make sure this is a lichess problem:

1. Install CuteChess: https://github.com/cutechess/cutechess/releases
2. Open CuteChess and open the Engine Debug window (View -> Engine Debug)
3. Have your engine play a game against itself.
4. Save the engine log to a file: right-click Engine Debug window -> Save Log to File ...
5. Check the saved log for instamoves by searching for "depth 0"

If instamoves happen in CuteChess, then it is more likely there is a bug in the engine and not lichess.

**Comment by uwuplant** [comment]
After further testing, it seems to be a quirk with Stockfish and its Move Overhead option.
