### ISSUE TITLE
Issues with config.yml (options being ignored or resulting in unexpected errors)

### ISSUE THREAD

**Issue by danegraphics** [ShailChoksi/lichess-bot#466]
Currently, I have this in my config:
```
  uci_options:               # Arbitrary UCI options passed to the engine.
    go_commands:             # Additional options to pass to the UCI go command.
      nodes: 1               # Search so many nodes only.
```
However, when I run it with -v, it shows that it's sending `go movetime 10000` instead of `go nodes 1`.

Is there a possible reason it is ignoring these options?

---

Another issue I'm running into is that if I specify any engine options, I get the errors:
```
2022-04-19 16:19:48,971:   Using selector: KqueueSelector
2022-04-19 16:19:48,975:   Using PollingChildWatcher
2022-04-19 16:19:48,987:   <UciProtocol (pid=11826)>: Connection made
2022-04-19 16:19:48,988:   <UciProtocol (pid=11826)>: << uci
2022-04-19 16:19:49,002:   <UciProtocol (pid=11826)>: Process exited
2022-04-19 16:19:49,003:   <UciProtocol (pid=11826)>: Connection lost (exit code: -6, error: None)
2022-04-19 16:19:49,004:   Backing off create_engine(...) for 2.0s (chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: -6))
```
and the engine never runs.

The options I'm running (which work if I run the engine from the command line) are:
```
  engine_options:            # Any custom command line params to pass to the engine.
    randombyp: true
    policy-softmax-temp: 1.0
```
My expectation is that when it starts the engine, it's running `./engines/lc0 --randombyp=true --policy-softmax-temp=1.0`, which would work.

**Comment by danegraphics** [comment]
Side note: Is there anyway to get lichess-bot to log the command it's using to start the engine? And to log any of the config options that it sees as set?

**Comment by danegraphics** [comment]
For the go options, I searched the source code and found that the go command for the first move is always going to be go movetime 10000. It's not a graceful solution since it ignores any and all options that are more restrictive than that, but I guess it works. I'll just change it in my local copy.

As for the engine options, they also happen to be able to be set in the uci options, so I set them there instead. But it definitely shouldn't crash when setting engine options.

I've got it working for me, however, these are definitely issues that should be addressed.

**Comment by MarkZH** [comment]
You're right on all counts. I'll need some time to think about how to incorporate `go` commands into the first move (and correspondence moves, now that I look at it).

If you want to log the engine command, you can add `logger.debug(f"Starting engine: {' '.join(commands)}")` just above `return Engine(...)` on line 36.

**Comment by MarkZH** [comment]
As for why your engine crashes, I would guess that the cause is that the `--randombyp` option gets a value of `True` rather than `true` (uppercase vs. lowercase). Try putting quotes around `true` in your config file.

**Comment by MarkZH** [comment]
Can you test the linked pull requests and let me know if they work?

**Comment by MarkZH** [comment]
> And is there a way to have it test starting the engine and asking for a move without me having to challenge it through lichess?

Sign into lichess with your bot's account and challenge the computer.

**Comment by uwuplant** [comment]
That doesn't work anymore, at least on my bots.



> > And is there a way to have it test starting the engine and asking for a move without me having to challenge it through lichess?
> 
> Sign into lichess with your bot's account and challenge the computer.

**Comment by AttackingOrDefending** [comment]
With my bot, it didn't work last week but it works today ([example game](https://lichess.org/GcaErHak)). I don't know why this is happening. You can open an issue in the [lichess repo](https://github.com/lichess-org/lila).
