### ISSUE TITLE
Suggestion: Workflow tests with Python

### ISSUE THREAD

**Issue by TheYoBots** [ShailChoksi/lichess-bot#475]
Currently the GitHub workflow tests lichess bot with pytest ([file permalink](https://github.com/ShailChoksi/lichess-bot/blob/master/.github/workflows/python-test.yml)). I think it would be much easier to test with python instead(?) by running running something like `python test_bot/test_bot.py`(?).

**Comment by AttackingOrDefending** [comment]
`pytest-timeout` doesn't work when running from `python`, so the tests won't end if there is a bug that doesn't let the games finish. Also, after a test fails `pytest` still runs the other tests, while with `python` the tests would end after the first `assert False`. Why do you think that it would be easier to test with `python`?

**Comment by TheYoBots** [comment]
I was wondering if it would remove the extra dependencies and require lesser code?
