### ISSUE TITLE
Accept Ultra Bullet Time Control 

### ISSUE THREAD

**Issue by TheBlackPlague** [ShailChoksi/lichess-bot#491]
Hello.

From what the README configuration documentation suggests... Ultra Bullet Time Control isn't supported. Any reason as to why?

**Comment by uwuplant** [comment]
lichess doesn't allow bots to play that TC for server strain reasons iirc

Jul. 2, 2022 12:38:17 p.m. Shaheryar Sohail ***@***.***>:

**Comment by MarkZH** [comment]
@uwuplant is right. [From the founder of lichess](https://lichess.org/forum/off-topic-discussion/bots-2#8):

> It's because bots make one HTTP request per move, and ultrabullet requires playing so many moves in so little time that they were hitting rate limits.

**Comment by TheBlackPlague** [comment]
I see. Thank you.
