### ISSUE TITLE
Error writing game record

### ISSUE THREAD

**Issue by AttackingOrDefending** [ShailChoksi/lichess-bot#502]
The bot failed to write the game record for https://lichess.org/WzU3jHmv. It got
```
2022-07-20 10:08:55,173 __mp_main__ WARNING Error writing game record: AssertionError('san() and lan() expect move to be legal or null, but got d5h1 in 8/5pk1/6p1/r3Pb1p/5P1P/6P1/3R1K2/7B w - - 9 48')
```
The move `d5h1` had been made in the previous fen `8/5pk1/6p1/2r1Pb1p/5P1P/6P1/3R1K2/7B b - - 8 47`. Maybe it has something to do with the draw offer by my bot.
Logs:
[log.txt](https://github.com/ShailChoksi/lichess-bot/files/9147556/log.txt)

**Comment by MarkZH** [comment]
We can do both: report the bug to lichess and handle the current situation. I'll start working on the workaround soon.
