### ISSUE TITLE
Bot becomes unresponsive in correspondence games

### ISSUE THREAD

**Issue by xor-ebx-ebx** [ShailChoksi/lichess-bot#507]
I'm seeing this message when my bot checks in on correspondence games
```
Backing off play_game(...) for 3.0s (TypeError: is_engine_move() missing 1 required positional argument: 'board')
```
Then the bot becomes completely unresponsive, presumably stuck in a loop

After a quick grep, I saw line 364 in lichess-bot.py reads
```
                if is_correspondence and not is_engine_move(game, board) and game.should_disconnect_now():
```
Changing that to
```
                if is_correspondence and not is_engine_move(game, prior_game, board) and game.should_disconnect_now():
```
Appears to fix the problem.  Seems like this is just an oversight with an easy fix, but I have no idea what other implications my fix may have

**Comment by MarkZH** [comment]
Good catch. Your fix is correct. I'll implement it as soon as I can.
