### ISSUE TITLE
there's no file named config.yml.default

### ISSUE THREAD

**Issue by Jsjnsns78** [ShailChoksi/lichess-bot#516]

**Comment by MarkZH** [comment]
1. Are you using Windows?
2. Do you see a config.yml file?

If both answers are yes, then the .default part of the file name is probably hidden. You can change this behavior by looking through the View menu at thr top if the folder Window.

If this doesn't help, you can download the file from here: https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/config.yml.default
