### ISSUE TITLE
how to increase the speed?

### ISSUE THREAD

**Issue by realpritam** [ShailChoksi/lichess-bot#520]

**Comment by MarkZH** [comment]
What do you want to be faster?

**Comment by Jsjnsns78** [comment]
> What do you want to be faster?

like it's making moves very slowly, how can i increase that?

**Comment by MarkZH** [comment]
Run lichess-bot with `-v -l log.txt`. After a game is played, copy the contents of log.txt here.

Also, copy your config.yml file here. Make sure to delete your token before posting.
