### ISSUE TITLE
Bot crashes when someone offers him a correspondence game

### ISSUE THREAD

**Issue by alex65536** [ShailChoksi/lichess-bot#521]
The error message is as follows:

```
2022-08-01 23:07:00,959 __main__ ERROR Quitting lichess-bot due to an error:
Traceback (most recent call last):
  File "/opt/sofcheck/lichess-bot/lichess-bot.py", line 923, in <module>
    start_lichess_bot()
  File "/opt/sofcheck/lichess-bot/lichess-bot.py", line 916, in start_lichess_bot
    start(li, user_profile, CONFIG, logging_level, args.logfile)
  File "/opt/sofcheck/lichess-bot/lichess-bot.py", line 196, in start
    chlng = model.Challenge(event["challenge"])
  File "/opt/sofcheck/lichess-bot/model.py", line 19, in __init__
    self.challenger_title = self.challenger.get("title")
AttributeError: 'NoneType' object has no attribute 'get'
```
https://github.com/ShailChoksi/lichess-bot/blob/9e96b98785aa3502da19acec961e93d490a4aa83/model.py#L9-L23

Here, `c_info["challenger"]` is apparently equal to `None`, so crash happens.

**Comment by MarkZH** [comment]
Thanks for the report. Two things:

1. If you can, please try to recreate the error with verbose logging (`-v` on the command line) so we can see the full challenge information.
2. Please test PR #522, and make sure it fixes the error.

**Comment by MarkZH** [comment]
Also, how was the challenge started? Who issued the challenge and who was the opponent?

**Comment by MarkZH** [comment]
@alex65536 Please reopen if the problem happens again.

**Comment by alex65536** [comment]
Thanks for the quick fix :) Before the issue was closed, I had been using a similar patch, like adding

```python
if self.challenger is None:
    self.challenger = {}
```

and observed no problems with it.
