### ISSUE TITLE
Bot starting multiple engine instances for one game

### ISSUE THREAD

**Issue by uwuplant** [ShailChoksi/lichess-bot#523]
Hi! I'm trying to get my Lc0 bot set up again for some testing, but there's a pretty annoying issue I'm coming across. The bot seems to be constantly starting engine instances during games.

 edit: also persists after game ends. 
![image](https://user-images.githubusercontent.com/26153075/182448324-d6a18bb3-c5fe-4c98-bac4-2cea1f6e1253.png)

Log: https://hst.sh/ugelenenip

**Comment by uwuplant** [comment]
note: also seems to be restarting engine after every move.

**Comment by MarkZH** [comment]
This is very strange. Your bot received multiple `gameStart` messages for the same game and tried to play multiple copies of the same game simultaneously. It's not that a new bot was initiated after every move, but that several copies of your bot were all trying to play the first move of game `qU97vRiR`. Notice that none of the `gameState` messages have any moves.

I find all of the copies of these lines at the beginning of your log suspicious:
```
DEBUG    https://lichess.org:443 "GET /api/stream/event HTTP/1.1" 200 None  connectionpool.py:456
DEBUG    Starting new HTTPS connection (1): lichess.org:443                 connectionpool.py:1001
```
Does this happen every time you start lichess-bot?

**Comment by uwuplant** [comment]
Yup, it was happening every time I started it. Interestingly enough, it's no longer happening now. Will close for now, but if it happens again, then there's definitely something going on.

Aug. 3, 2022 6:30:58 a.m. Mark Harrison ***@***.***>:

**Comment by uwuplant** [comment]
just happened again.
[botlog.txt](https://github.com/ShailChoksi/lichess-bot/files/9264081/botlog.txt)

**Comment by uwuplant** [comment]
aaaand closing again. either it's something to do with the time of day (very improbable), or something that got fixed with a system reboot (much more probable.) will probably keep this open for another day, if it happens again (again), then I'll be back :D

**Comment by MarkZH** [comment]
Another thing to try is updating the lichess-bot dependencies with
```
pip install -r requirements.txt --upgrade
```
Maybe there were some bugs fixed in the newer versions. Adding `--force-reinstall` might do something useful, too.

**Comment by uwuplant** [comment]
hasn't happened to me again, so hopefully it's resolved now. thank you for the help!
