### ISSUE TITLE
Should not accept challenge from blocked users

### ISSUE THREAD

**Issue by fabriciodosanjossilva** [ShailChoksi/lichess-bot#537]
As a challenge is received, linux-bot should decline if challenger is blocked. This information is available on challenger public info (https://lichess.org/api/user/{user}), on field "blocking".

**Comment by fabriciodosanjossilva** [comment]
@MarkZH,

For me, blocking a user means that I don't want to interact wih him/her anymore.

It seems that what you have done is equivalent to "don't challenge blocked users", which is fine. Although your commit title seems innacurate.

But what I am reporting here is different from what you have done. Here I report that after blocking a user, it does not seem right to accept a challenge from him/her. It's a related issue, but to the same.

**Comment by MarkZH** [comment]
That branch is a work-in-progress. That branch also doesn't work since the information about blocking is not provided with the data called for (online bots). I'm testing other methods.

**Comment by MarkZH** [comment]
At the moment, this is not possible to implement since the Lichess API does not provide this information to requests with access tokens. I've submitted [an issue](https://github.com/lichess-org/api/issues/200) to change this.

**Comment by fabriciodosanjossilva** [comment]
I see now that my statement that the blocking information was publicly available was innacurate. I tested that in the browser, not using the the access token. You're right, when using access token, the information is not delivered.

**Comment by MarkZH** [comment]
@fabriciodosanjossilva I've submitted a PR (linked above) to stop bots from challenging bots they have blocked. Please test and let me know if it works for you.

**Comment by fabriciodosanjossilva** [comment]
I'll test it, thanks. But I will only be available to do this next weekend. I'll let you know.

**Comment by fabriciodosanjossilva** [comment]
@MarkZH, I've been using this feature for about one hour or two. This will take much longer so I can say that it is working. So far, so good. I'll let you know if anything unexpectedly happens.

Thanks, again.
