### ISSUE TITLE
Matchmaking should avoid challenging user that consistently declines challenges

### ISSUE THREAD

**Issue by fabriciodosanjossilva** [ShailChoksi/lichess-bot#538]
After challenging a user via Matchmaking, if challenged user declines the challenge, linux-bot should "remember" that for awhile, avoiding annoying the user and wasting time. I'm getting declines quite frequently from bots that: are not accepting challenges with the request time parameters; not accepting challenges form bots; or are not accepting challenges at all.

As an implementation suggestion, this can be done as a "no contact" time window, where no challenge is to be sent to same user, with the same time parameters, within this time window. The window should start low (say 5 minutes) and increase exponentially (doubling on every next decline). An upper limit may be set (say 24h). It would be great if this window (for each user) is persisted, surviving a lichess-bot restart.

It seems that public user data does not contain challenge restrictions. If this information were available, challenges that will be declined because of this public restrictions could be avoided upfront. I see that often users report their requirements by text on their profile. It's a shame that these restrictions are not available via API. This might turn into a Lichess API enhancement request. But for now, I think the best would be to implement the above described control.

**Comment by MarkZH** [comment]
I've implemented most of this request in the linked PR. The delay window starts at an hour after a challenge is declined and increases by an hour after each subsequent decline. I figured that the settings that cause a bot to decline a challenge do not change that often, so a minutes-long delay would be too short at the start. I didn't write code to persist the delays through lichess-bot restarts since this would add complication with little benefit.

**Comment by mheinzel** [comment]
This seems like an effective way to reduce sending unsuccessful challenge request.
The only potential downside I see occurs in combination with the recently added random choice of time control: If an opponent doesn't play one time control, we would also stop sending challenges for the others.

This doesn't seem ideal, but keeping track of timers for each type of time control separately would complicate the code quite a bit. Maybe one could instead not delay further challenges if the decline reason was the time control?

**Comment by fabriciodosanjossilva** [comment]
@MarkZH, thanks again. Since there will be no persistent suspension, I suggest rasing the initial suspension time from 1 hour to 2 hours.

@mheinzel, about the downside, you are right. I think that there are two strategies that can be used to mitigate this side effect. They can be used independently or, better yet, together.

Strategy 1: The suspension should consider the tuple [user, time_total, time_increment]. This way lichess-bot will try again for the same user when using a different time setting. For example, while using lichess-bot, I only use 4 different vales for challenge_initial_time and one fixed for challenge_increment. Even for a user who does not accept challenges, I would stop bothering him/her with challenges in just 4 tries. This strategy can mitigate the downside mentioned by @mheinzel, but may try a few times unnecessarily for bots that are not accepting any time settings. Strategy 2 would help in these cases.

Strategy 2: lichess-bot should try to interpret the error message that comes with the decline. Most bots use english texts and many of them use lichess-bot. So, but checking specific text strings, the suspension would be precise for many cases (high hit ratio), but not for those using not common text.  Strategy 1 would handle these cases.

**Comment by fabriciodosanjossilva** [comment]
For strategy 2 described above, the event is usually:

Event: {'type': 'challengeDeclined', ...  'declineReason': "I'm not accepting challenges with this time control."}}
Event: {'type': 'challengeDeclined', ...  'declineReason': "I'm not accepting challenges from bots."}}
