### ISSUE TITLE
Text color garbled after game finishes, when on verbose mode

### ISSUE THREAD

**Issue by fabriciodosanjossilva** [ShailChoksi/lichess-bot#539]
When using verbose mode (python lichess-bot.py -v), lichess-bot displays debug text lines, using different colors to differentiate different info. When game finishes, there is an incorrect change to default text color, leading to incorrect colored text from then on. Sometimes text color turns to dark blue, which makes text unreadable. Restarting is the only solution.

In the attached image, the default white text turns into cyan. Red arrows show incorrect color.

It seems that some color control code is set, but not unset.
![wrong text color](https://user-images.githubusercontent.com/18731229/184226343-0f4f86b3-d3fa-4738-976c-fd22c9371544.png)

**Comment by MarkZH** [comment]
We discussed this problem in PR #506. It seems like CMD and PowerShell cannot handle logging messages from multiple threads without mashing messages together. However, [Windows Terminal](https://docs.microsoft.com/en-us/windows/terminal/install) seems to have fixed this problem. Try installing that and tell us if that fixes the problem.

**Comment by fabriciodosanjossilva** [comment]
I tested in Windows Terminal. It worked fine. I did not have the text color issue.

If this is a known limitation of PowerShell and CMD, and it seems that it is not worth to make lichess-bot work with these terminals, then leave it that way and you may close this Github issue.

Thanks!

**Comment by MarkZH** [comment]
I don't know if it's a limitation of PowerShell/CMD or of the colorizing library we're using (Rich). I may file a bug report with the Rich library at some point in the future.

**Comment by MarkZH** [comment]
Note towards a possible solution:

The function [`detect_legacy_windows()`](https://rich.readthedocs.io/en/stable/reference/console.html#rich.console.detect_legacy_windows) in `rich.console` returns `False` for cmd.exe within windows terminal and `True` for cmd.exe for cmd.exe without. Maybe give the [`RichHandler`](https://rich.readthedocs.io/en/stable/reference/logging.html#rich.logging.RichHandler) a [`Console`](https://rich.readthedocs.io/en/stable/reference/console.html#rich.console.Console) instance which should automatically detect whether a legacy terminal is needed (or use the detect function explicitly).

**Comment by MarkZH** [comment]
That didn't work, so I'm all out of ideas. I guess the solution to this is to use Windows Terminal.

**Comment by fabriciodosanjossilva** [comment]
I'm using Windows Terminal for a few days. It works fine.

Keep lichess-bot unchanged. I suggest to put a note in the instructions (README.md) mentioning that is advised to use Windows Terminal in order to avoid text formating issues.

**Comment by MarkZH** [comment]
This should be fixed with PRs #777 and #800.
