### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FatFritz2** [ShailChoksi/lichess-bot#560]
Is there a way for my bot not to accept no incremental at bullets (1+0, 1/2+0 or 2+0) because it moves kinda slow

**Comment by MarkZH** [comment]
In the `challenge` section of the configuration file there's a setting for the minimum increment value: `min_increment`. Change this to 1 to have a minimum increment of 1 second.

Every configuration has a description in the [README](https://github.com/ShailChoksi/lichess-bot/blob/master/README.md) file.

**Comment by FatFritz2** [comment]
THANKS GOD
