### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FatFritz2** [ShailChoksi/lichess-bot#565]
Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/W7uPB5uy/chat)

**Comment by MarkZH** [comment]
What's the problem?

**Comment by FatFritz2** [comment]
The bot seems not chatting when i hit !eval command

**Comment by AttackingOrDefending** [comment]
Can you upload the logs from the game? You can run `python lichess-bot.py -v -l logs.txt`, so the logs will be saved.
