### ISSUE TITLE
Bot randomly hangs

### ISSUE THREAD

**Issue by uwuplant** [ShailChoksi/lichess-bot#573]
Hello!
I've been having a strange issue ever since I updated my bot instance to the latest commit (85f5285). I've been noticing that after any time from a few hours to a couple days after starting the bot, it simply doesn't respond to challenges anymore. 
![Screenshot_20220921-110126_JuiceSSH](https://user-images.githubusercontent.com/26153075/191540463-45bd01bb-ab7d-4435-86ca-805cdb3567e9.jpg)
I have modified the bot slightly, but the only change is in the engine wrapper, and thus it shouldn't have any effect. (never has in the past)

Thank you!

update: possibly related to #222?

**Comment by MarkZH** [comment]
Is your bot not sending challenges, not receiving challenges, or both?

When your bot gets to this state, what happens when you challenge your bot with your own human account?

**Comment by uwuplant** [comment]
It seems to have mostly resolved itself, but:

It wouldn't accept or deny any challenges, no matter what I tried. The only way to fix it was a restart.

**Comment by MarkZH** [comment]
Have you noticed this happening still? If so, the latest update should restart lichess-bot if it loses communication with lichess.

**Comment by uwuplant** [comment]
nope, hasn't happened again. if anything happens, I'll reopen (but I don't expect to have to do that)
