### ISSUE TITLE
Backing off play game

### ISSUE THREAD

**Issue by OlloVeno** [ShailChoksi/lichess-bot#583]
Backing off play game(...) for 8.9s (chess.engine.Engine Error: engine does not support option Move Overhead (available options: Hash, _common.py:105 Threads, MultiPV, Clear Hash, Ponder, UseBook, VerboseBook, MainBookFile, TimeBuffer))

**Comment by MarkZH** [comment]
In the `engine: uci_options:` section of your config file, remove the `Move Overhead` line. The error message tells you the possible options you can put there.

**Comment by OlloVeno** [comment]
Yes, I just removed this line, and it all worked. Thanks for the help.
