### ISSUE TITLE
Throtling incoming requests

### ISSUE THREAD

**Issue by bec-ca** [ShailChoksi/lichess-bot#592]
Once in a while, a bot will send requests one after the other. As soon as the game ends they send another one.

I would like my bot to stop accepting requests from that same bot if my bot already played the challenging bot many times recently, so my bot can have a chance to play other bots.

I don't think that feature is currently available. I would be happy to contribute with code. Let me know if you like to have this.

**Comment by MarkZH** [comment]
Do these challenges from the same bot stop challenges from other bots? What do you have for `concurrency:` in the `challenge:` section of your config file? If that number is at least 2, then your bot should be able to accept challenges from other bots.

I do understand that constantly playing the same opponent over and over again can be annoying, so it would probably be worth it to handle this. Go ahead and open a PR and we'll discuss the idea.

**Comment by bec-ca** [comment]
It doesn't stop other incoming challenges, but they rarely come. Most of the games my bot plays are from  matchmaker, those do stop being sent I believe. But there are also other reasons not to play the same bot over and over, eg, a bot that is way stronger, keep defeating mine, they are probably just farming rating?

Ok, I will try to put a PR together soon.

**Comment by MarkZH** [comment]
Closed by #593. Thanks!
