### ISSUE TITLE
Decline or limit rematches from other bots

### ISSUE THREAD

**Issue by kurt1288** [ShailChoksi/lichess-bot#597]
My bot ran into a situation where another bot was requesting a rematch after every game and apparently the request is always accepted. I didn't want to continue playing that bot for a few reasons, but stopping it proved not easy.

I tried blocking the other bot, but apparently that does not prevent rematch requests. I could have turned off my bot, but there were other games in play that I didn't want to end. The only way I was able to finally stop the cycle was to log in as my bot and spam click the area where the "decline" button appear on the rematch request.

Having a way to automatically decline rematch requests, either all or just those from bots, would seem helpful.

**Comment by MarkZH** [comment]
Would PR #593 solve your problem? You would be able to specify, for example, that no one bot can challenge yours more than once per hour (or some other frequency).

**Comment by kurt1288** [comment]
That probably would achieve the ask, yes.

Do you know if rematches actually trigger the "challenge" event though?

**Comment by MarkZH** [comment]
I think they do. If you run lichess-bot with the `-v` and `-l log.txt` options, then you can see the messages passed between your bot and lichess. It would be interesting to see the messages leading up to a rematch.

Now that I'm looking at the API, there is a way to [create a challenge](https://lichess.org/api#tag/Challenges/operation/challengeCreate) with no option for a rematch. I'll think about this.

**Comment by MarkZH** [comment]
Closed by #593.
