### ISSUE TITLE
SyzygyPath in configs

### ISSUE THREAD

**Issue by noobpwnftw** [ShailChoksi/lichess-bot#602]
https://github.com/ShailChoksi/lichess-bot/blob/ea4ea5619d472745ce8c9c28591cd238015712c2/config.yml.default#L56-L62

Maybe it is better to have boilerplate `SyzygyPath` uci option on par with other references. It also seems unnecessary to have the bot read any local tablebases if the engine supports reading them.

**Comment by MarkZH** [comment]
The idea behind this section was to allow engines that don't natively support these endgame tablebases to access them through lichess-bot (Issue #314, PR #533). Even if an engine supports the UCI protocol, that doesn't mean it knows how to read these resources.

**Comment by noobpwnftw** [comment]
A common mistake from users is that having local tablebase path set here gets passed along to the engines, which it won't.

**Comment by AttackingOrDefending** [comment]
It seems like a good idea to have the TBs in one place.

We can add two parameters (e.g. `engine_use` and `local_use`), so that the user can specify if the TBs should be used by the engine, lichess-bot or both.

**Comment by MarkZH** [comment]
@AttackingOrDefending I don't think that will work. The TBs and books that engines use directly need to be listed in the `uci_options` or `xboard_options` sections. Granted, both stockfish and leela use the option `SyzygyPath` for the option name, but this is not standardized and neither is it standardized for Xboard engines.

Maybe we should add `SyzygyPath` as an option under `uci_options` in config.yml.default to indicate the proper place. We could also put a note near the `lichess_bit_tbs` that the engine is not consulted when these TBs are used.

**Comment by AttackingOrDefending** [comment]
Adding it under `uci_options` and adding comments seems to be good enough since some engines also have `Use syzygy` and I guess other engines have other similar options. Also, they may lead to a slow-down if the default `SyzygyProbeDepth` is low (e.g. 1), especially if the user is using an HDD.
