### ISSUE TITLE
Filenotfound

### ISSUE THREAD

**Issue by Aseurw** [ShailChoksi/lichess-bot#606]
I am getting this error when I try to start the program
 ERROR    Quitting lichess-bot due to an error:                                   lichess-bot.py:733
                             Traceback (most recent call last):
                               File "D:\Download\chess hack\big
                             boss\lichess-bot-master\lichess-bot.py", line 730, in <module>
                                 start_lichess_bot()
                               File "D:\Download\chess hack\big
                             boss\lichess-bot-master\lichess-bot.py", line 708, in start_lichess_bot
                                 CONFIG = load_config(args.config or "./config.yml")
                               File "D:\Download\chess hack\big boss\lichess-bot-master\config.py",
                             line 25, in load_config
                                 with open(config_file) as stream:
                             FileNotFoundError: [Errno 2] No such file or directory: './config.yml'
![image_2022-11-25_105738056](https://user-images.githubusercontent.com/74925544/203930139-35429121-2269-40ea-9fc6-198fccce4ec6.png)

**Comment by mheinzel** [comment]
Do you have a file called `config.yml` in that folder? You can create it by copying the `config.yml.default` file and changing it as needed (as explained near the end of the [installation instructions](https://github.com/ShailChoksi/lichess-bot#windows)).

**Comment by Aseurw** [comment]
yes I have it
![image](https://user-images.githubusercontent.com/74925544/204006741-0aec6545-bf59-4cc4-8a26-41be3be0c351.png)

**Comment by mheinzel** [comment]
It looks like it, but that is because Windows hides the file extension. It shows `config.yml` but next to it says "DEFAULT File". So it's actually `config.yml.default`.

Can you try copying it? You can also do it in the Command Prompt with something like `copy config.yml.default config.yml`.
