### ISSUE TITLE
Can lichess-bot use an opening book without engine support?

### ISSUE THREAD

**Issue by thomasahle** [ShailChoksi/lichess-bot#630]
It's unclear to me, from the documentation, whether the engine needs to have support for opening books, or if the lichess-bot code itself supports this?

By lichess-bot supporting opening books, I mean as it says in the UCI protocol: "by default all the opening book handling is done by the GUI".

If I enable the book in config.yml, will my bot automatically start using a book? Or do I need to implement code into the bot itself?

**Comment by thomasahle** [comment]
Thank you!

This still requires me to make/find a book.bin file, right?

If I enable `[chessdb_book](https://github.com/ShailChoksi/lichess-bot/blob/fb56303cda33ef4102765a383f20fdd06e22121c/config.yml.default#L40 )`, does that work with just a single line changed, without configuring anything else?

**Comment by MarkZH** [comment]
Yes to both.

**Comment by thomasahle** [comment]
Thank you!
